  CREATE OR REPLACE FORCE VIEW "FERREDB"."LISTAR_EMPRESABSC" ("CÓDIGO", "RAZÓN SOCIAL") AS 
  SELECT "ID_CIA","RAZON_SOCIAL"
    FROM TBL_EMPRESA
ORDER BY ID_CIA;


create or replace PROCEDURE "LISTAR_TBL_EMPRESABASIC" (REGISTROS OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN REGISTROS FOR SELECT * FROM LISTAR_EMPRESABSC;
END LISTAR_TBL_EMPRESABASIC;

CREATE OR REPLACE FORCE VIEW "FERREDB"."LISTAR_EMPRESABSC" ("CÓDIGO", "PERSONERIA","Nº IDENTIFICACION", "RAZÓN SOCIAL", "TIPO DE COMPAÑIA") AS 
SELECT TBL_EMPRESA.ID_CIA, TBL_TIPO_IDENTIFICACION.PERSONERIA, TBL_EMPRESA.NUM_ID, TBL_EMPRESA.RAZON_SOCIAL, TBL_TIPO_CIA.TIPO_EMPRESA
FROM TBL_EMPRESA, TBL_TIPO_IDENTIFICACION,TBL_TIPO_CIA
WHERE TBL_TIPO_IDENTIFICACION.ID_TIPO_IDENTIFICACION = TBL_EMPRESA.ID_TIPO_IDENTIFICACION AND  TBL_TIPO_CIA.ID_TIPO_CIA = TBL_EMPRESA.ID_TIPO_CIA;


/*ORIGINAL*/
CREATE OR REPLACE FORCE VIEW "FERREDB"."LISTAR_EMPRESABSC" ("CÓDIGO", "Nº IDENTIFICACION", "RAZÓN SOCIAL", "PERSONERIA") AS 
  SELECT TBL_EMPRESA.ID_CIA, TBL_EMPRESA.NUM_ID, TBL_EMPRESA.RAZON_SOCIAL, TBL_TIPO_IDENTIFICACION.PERSONERIA
FROM TBL_EMPRESA, TBL_TIPO_IDENTIFICACION
WHERE TBL_TIPO_IDENTIFICACION.ID_TIPO_IDENTIFICACION = TBL_EMPRESA.ID_TIPO_IDENTIFICACION;



/*ACTIVAR EMPRESA*/
CREATE OR REPLACE PROCEDURE"ACTIV_EMPRESA" 
(IDEMP IN NUMBER)
AS
VARID number:=IDEMP;
BEGIN
  UPDATE TBL_EMPRESA 
  SET ESTADO = 'ACTIVO'
  WHERE ID_CIA = IDEMP;
END;

/*DESACTIVAR EMPRESA*/
CREATE OR REPLACE PROCEDURE  "DESACTIV_EMPRESA" 
(IDEMP IN NUMBER)
AS
VARID number:=IDEMP;
BEGIN
  UPDATE TBL_EMPRESA 
  SET ESTADO = 'INACTIVO'
  WHERE ID_CIA = IDEMP;
END;

/*BORRAR EMPRESA*/
CREATE OR REPLACE PROCEDURE  "BORRAR_TBL_EMPRESA" 
(IDEMP IN NUMBER)
AS 
  VARID number:=IDEMP;
BEGIN
    DELETE FROM TBL_EMPRESA
    WHERE ID_CIA = IDEMP;
END BORRAR_TBL_EMPRESA;


/*---------- ACTUALIZAR EMPRESA ----------*/
CREATE OR REPLACE PROCEDURE "ACTUALIZAR_TBL_EMPRESA" 
(ID_CIA IN NUMBER, TIPO_CIA IN VARCHAR2, DESCRIP IN VARCHAR2)
AS
  VARID NUMBER:= ID_CIA;
  VARTIPOCIA VARCHAR2(20):= TIPO_CIA;
  VARDESCRIP VARCHAR (50):= DESCRIP;
  
BEGIN
      UPDATE TBL_EMPRESA
      SET TIPO_EMPRESA = TIPO_CIA, DESCRIPCION = DESCRIP
      WHERE ID_TIPO_CIA = VARID;
END ACTUALIZAR_TBL_TIPO_CIA;

/*--------------------------------------------------*/