/*CRACION DE VISTA*/
CREATE OR REPLACE FORCE VIEW "FERREDB"."LISTAR_TIPOID" ("ID_TIPO_IDENTIFICACION", "PERSONERIA") AS 
SELECT "ID_TIPO_IDENTIFICACION", "PERSONERIA"
FROM TBL_TIPO_IDENTIFICACION
ORDER BY ID_TIPO_IDENTIFICACION;

/*PROCEDIMIENTO ACTUALIZAR*/

CREATE OR REPLACE PROCEDURE "ACT_TBL_TIPOID" 
(IDTIPO IN NUMBER, PERSON IN VARCHAR2)
AS
  VARID NUMBER:= IDTIPO;
  VARPERSO VARCHAR2(20):= PERSON;
BEGIN
      UPDATE TBL_TIPO_IDENTIFICACION
      SET PERSONERIA = VARPERSO
      WHERE ID_TIPO_IDENTIFICACION = VARID;
END ACT_TBL_TIPOID;

/*PROCEDIMIENTO BORRAR*/

CREATE OR REPLACE PROCEDURE "BORRAR_TBL_IDPERSO" 
(ID_PERSO IN NUMBER)
AS 
  VARID number:=ID_PERSO;
BEGIN
    DELETE FROM TBL_TIPO_IDENTIFICACION
    WHERE ID_TIPO_IDENTIFICACION = VARID;
END BORRAR_TBL_IDPERSO;

/*PROCEDIMIENTO BUSCAR*/
CREATE OR REPLACE PROCEDURE "BUSCAR_TBL_TIPOIDENTIF" 
(TIPOID IN TBL_TIPO_IDENTIFICACION.ID_TIPO_IDENTIFICACION%TYPE, 
REGISTROS OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN REGISTROS FOR SELECT ID_TIPO_IDENTIFICACION, PERSONERIA
    FROM TBL_TIPO_IDENTIFICACION
    WHERE PERSONERIA LIKE '%' ||TIPOID|| '%'
    ORDER BY ID_TIPO_IDENTIFICACION;
END BUSCAR_TBL_TIPOIDENTIF;

/*PROCEDIMIENTO INSERTAR*/
CREATE OR REPLACE PROCEDURE  "INS_TBL_TIPO_IDENTIF" (IDTIPO IN NUMBER, NOMB_ID IN VARCHAR2 )
AS 
BEGIN
    INSERT INTO TBL_TIPO_IDENTIFICACION(ID_TIPO_IDENTIFICACION,PERSONERIA)
    VALUES (IDTIPO, NOMB_ID);
    COMMIT;
END INS_TBL_TIPO_IDENTIF;

/*PROCEDIMIENTO LISTAR*/

CREATE OR REPLACE PROCEDURE "LISTAR_TBL_TIPOID" (REGISTROS OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN REGISTROS FOR SELECT * FROM LISTAR_TIPOID;
END LISTAR_TBL_TIPOID;


