--------------------------------------------------------
-- Archivo creado  - lunes-agosto-10-2020   
--------------------------------------------------------
DROP TABLE "FERREDB"."TBL_BODEGAS" cascade constraints;
DROP TABLE "FERREDB"."TBL_CATEGORIA" cascade constraints;
DROP TABLE "FERREDB"."TBL_CLIENT_PROV" cascade constraints;
DROP TABLE "FERREDB"."TBL_DETALLE_DEV" cascade constraints;
DROP TABLE "FERREDB"."TBL_DETALLE_VENTA" cascade constraints;
DROP TABLE "FERREDB"."TBL_EMPRESA" cascade constraints;
DROP TABLE "FERREDB"."TBL_INGRESOS_DEV" cascade constraints;
DROP TABLE "FERREDB"."TBL_INVENTARIO_ARTICULOS" cascade constraints;
DROP TABLE "FERREDB"."TBL_MONEDAS" cascade constraints;
DROP TABLE "FERREDB"."TBL_PERMISOS_USUARIOS" cascade constraints;
DROP TABLE "FERREDB"."TBL_PROVINCIAS" cascade constraints;
DROP TABLE "FERREDB"."TBL_TIPO_CAMBIO" cascade constraints;
DROP TABLE "FERREDB"."TBL_TIPO_CIA" cascade constraints;
DROP TABLE "FERREDB"."TBL_TIPO_IDENTIFICACION" cascade constraints;
DROP TABLE "FERREDB"."TBL_TIPO_PERSONERIA" cascade constraints;
DROP TABLE "FERREDB"."TBL_TIPO_RELACION" cascade constraints;
DROP TABLE "FERREDB"."TBL_UND_MED" cascade constraints;
DROP TABLE "FERREDB"."TBL_USUARIOS" cascade constraints;
DROP TABLE "FERREDB"."TBL_VENTAS" cascade constraints;
DROP SEQUENCE "FERREDB"."SEC_ID_ARTICULO";
DROP SEQUENCE "FERREDB"."SECIDPROV";
DROP SEQUENCE "FERREDB"."SEC_ID_PROV_TBL_PROVINCIAS";
DROP VIEW "FERREDB"."LISTAR_CATEGORIAS";
DROP VIEW "FERREDB"."LISTAR_MONEDAS";
DROP VIEW "FERREDB"."LISTAR_PROVINCIAS";
DROP VIEW "FERREDB"."LISTAR_TBL_TIPO_CIA";
DROP VIEW "FERREDB"."LISTAR_UND_MEDIDA";
DROP FUNCTION "FERREDB"."EXISTE_PROV";
DROP PACKAGE "FERREDB"."PDTYPES";
DROP PACKAGE BODY "FERREDB"."INTEGRITYPACKAGE";
DROP PROCEDURE "FERREDB"."ACTIV_CATEGORIA";
DROP PROCEDURE "FERREDB"."ACTUALIZAR_TBL_CATEGORIA";
DROP PROCEDURE "FERREDB"."ACTUALIZAR_TBL_MONEDAS";
DROP PROCEDURE "FERREDB"."ACTUALIZAR_TBL_PROVINCIAS";
DROP PROCEDURE "FERREDB"."ACTUALIZAR_TBL_TIPO_CIA";
DROP PROCEDURE "FERREDB"."ACTUALIZAR_TBL_UND_MED";
DROP PROCEDURE "FERREDB"."BORRAR_TBL_CATEGORIA";
DROP PROCEDURE "FERREDB"."BORRAR_TBL_MONEDAS";
DROP PROCEDURE "FERREDB"."BORRAR_TBL_PROVINCIAS";
DROP PROCEDURE "FERREDB"."BORRAR_TBL_TIPO_CIA";
DROP PROCEDURE "FERREDB"."BORRAR_TBL_UND_MED";
DROP PROCEDURE "FERREDB"."BUSCAR_TBL_CATEGORIA";
DROP PROCEDURE "FERREDB"."BUSCAR_TBL_MONEDAS";
DROP PROCEDURE "FERREDB"."BUSCAR_TBL_PROVINCIAS";
DROP PROCEDURE "FERREDB"."BUSCAR_TBL_TIPO_CIA";
DROP PROCEDURE "FERREDB"."BUSCAR_TBL_UND_MEDIDAS";
DROP PROCEDURE "FERREDB"."DESACTIV_CATEGORIA";
DROP PROCEDURE "FERREDB"."INSERTAR_TBL_CATEGORIA";
DROP PROCEDURE "FERREDB"."INSERTAR_TBL_MONEDAS";
DROP PROCEDURE "FERREDB"."INSERTAR_TBL_PROVINCIAS";
DROP PROCEDURE "FERREDB"."INSERTAR_TBL_TIPO_CIA";
DROP PROCEDURE "FERREDB"."INSERTAR_TBL_UND_MED";
DROP PROCEDURE "FERREDB"."LISTAR_TBL_CATEGORIA";
DROP PROCEDURE "FERREDB"."LISTAR_TBL_MONEDAS";
DROP PROCEDURE "FERREDB"."LISTAR_TBL_PROVINCIAS";
DROP PROCEDURE "FERREDB"."LISTAR_TIPO_CIA";
DROP PROCEDURE "FERREDB"."LISTAR_UNIDADES_MEDIDA";
--------------------------------------------------------
--  DDL for Sequence SEC_ID_ARTICULO
--------------------------------------------------------

   CREATE SEQUENCE  "FERREDB"."SEC_ID_ARTICULO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SECIDPROV
--------------------------------------------------------

   CREATE SEQUENCE  "FERREDB"."SECIDPROV"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_ID_PROV_TBL_PROVINCIAS
--------------------------------------------------------

   CREATE SEQUENCE  "FERREDB"."SEC_ID_PROV_TBL_PROVINCIAS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table TBL_BODEGAS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_BODEGAS" 
   (	"ID_CIA" NUMBER(*,0), 
	"ID_INGRESO" NUMBER(*,0), 
	"ID_BODEGA" NUMBER(*,0), 
	"ID_ARTICULO" NUMBER(*,0), 
	"COD_BODEGA" VARCHAR2(10 BYTE), 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"UBICACION" VARCHAR2(100 BYTE), 
	"STOCK" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_CATEGORIA
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_CATEGORIA" 
   (	"ID_CATEGORIA" NUMBER(*,0), 
	"CATEGORIA" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"ESTADO" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_CLIENT_PROV
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_CLIENT_PROV" 
   (	"ID_CIA" NUMBER(*,0), 
	"ID_CLI_PROV" NUMBER(*,0), 
	"ID_TIPO_IDENTIFICACION" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"NUM_DOC" VARCHAR2(20 BYTE), 
	"ID_PROVINCIA" NUMBER(*,0), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"WEB" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_DETALLE_DEV
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_DETALLE_DEV" 
   (	"ID_ING_DEV" NUMBER(*,0), 
	"ID_INGRESO" NUMBER(*,0), 
	"ID_ARTICULO" NUMBER(*,0), 
	"CANTIDAD" NUMBER(*,0), 
	"PRECIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_DETALLE_VENTA
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_DETALLE_VENTA" 
   (	"ID_DETALLE_VENTA" NUMBER(*,0), 
	"ID_VENTA" NUMBER(*,0), 
	"ID_ARTICULO" NUMBER(*,0), 
	"PRECIO" NUMBER(11,2), 
	"DESCUENTO" NUMBER(11,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_EMPRESA
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_EMPRESA" 
   (	"ID_CIA" NUMBER(*,0), 
	"ID_TIPO_CIA" NUMBER(*,0), 
	"ID_TIPO_IDENTIFICACION" NUMBER(*,0), 
	"NUM_ID" VARCHAR2(20 BYTE), 
	"RAZON_SOCIAL" VARCHAR2(50 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"ID_PROVINCIA" NUMBER(*,0), 
	"DIRECCION" VARCHAR2(255 BYTE), 
	"TEL1" VARCHAR2(15 BYTE), 
	"TEL2" VARCHAR2(15 BYTE), 
	"FAX" VARCHAR2(15 BYTE), 
	"CP" VARCHAR2(10 BYTE), 
	"WEB" VARCHAR2(60 BYTE), 
	"E_MAIL" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_INGRESOS_DEV
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_INGRESOS_DEV" 
   (	"ID_INGRESO" NUMBER(*,0), 
	"ID_CIA" NUMBER(*,0), 
	"ID_CLI_PROV" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"TIPO_COMPROBANTE" VARCHAR2(20 BYTE), 
	"CONSECUTIVO" NUMBER(*,0), 
	"FECHA" DATE, 
	"IMPUESTO" NUMBER(11,2), 
	"TOTAL" NUMBER(11,2), 
	"ESTADO" VARCHAR2(20 BYTE), 
	"ID_VENTA" NUMBER(*,0), 
	"ID_BODEGA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_INVENTARIO_ARTICULOS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_INVENTARIO_ARTICULOS" 
   (	"ID_ARTICULO" NUMBER(*,0), 
	"ID_CATEGORIA" NUMBER(*,0), 
	"ID_BODEGA" NUMBER(*,0), 
	"CODIGO" VARCHAR2(50 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"ID_UND_MEDIDA" NUMBER(*,0), 
	"PRECIO_VENTA" NUMBER(11,2), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"IMAGEN" VARCHAR2(20 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_MONEDAS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_MONEDAS" 
   (	"ID_MONEDA" NUMBER, 
	"COD_MONEDA" VARCHAR2(10 BYTE), 
	"DESCRIPCION" VARCHAR2(70 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_PERMISOS_USUARIOS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_PERMISOS_USUARIOS" 
   (	"ID_ROL" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_PROVINCIAS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_PROVINCIAS" 
   (	"ID_PROVINCIA" NUMBER(*,0), 
	"PROVINCIA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_CAMBIO
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_TIPO_CAMBIO" 
   (	"ID_TC" NUMBER(*,0), 
	"ID_MONEDA" NUMBER(*,0), 
	"COMPRA" NUMBER(*,0), 
	"VENTA" NUMBER(*,0), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_CIA
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_TIPO_CIA" 
   (	"ID_TIPO_CIA" NUMBER(*,0), 
	"TIPO_EMPRESA" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_IDENTIFICACION
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_TIPO_IDENTIFICACION" 
   (	"ID_TIPO_IDENTIFICACION" NUMBER(*,0), 
	"PERSONERIA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_PERSONERIA
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_TIPO_PERSONERIA" 
   (	"ID_TIPO_PERSONERIA" NUMBER(*,0), 
	"PERSONERIA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_RELACION
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_TIPO_RELACION" 
   (	"ID_TIPO_RELACION" NUMBER(*,0), 
	"RELACION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_UND_MED
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_UND_MED" 
   (	"ID_UND_MEDIDA" NUMBER(*,0), 
	"COD_MEDIDA" VARCHAR2(15 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_USUARIOS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_USUARIOS" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"ID_ROL" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO_1" VARCHAR2(50 BYTE), 
	"APELLIDO_2" VARCHAR2(50 BYTE), 
	"ID_TIPO_DOCUMENTO" VARCHAR2(20 BYTE), 
	"NUM_IDENTIFICACION" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(255 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(15 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_VENTAS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_VENTAS" 
   (	"ID_CIA" NUMBER(*,0), 
	"ID_VENTA" NUMBER(*,0), 
	"ID_CLIENTE" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"ID_COMPROBANTE" VARCHAR2(10 BYTE), 
	"FECHA" DATE, 
	"HORA" DATE, 
	"IMPUESTO" NUMBER(10,2), 
	"TOTAL" NUMBER(10,2), 
	"ESTADO" CHAR(1 BYTE), 
	"ID_TC" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;

   COMMENT ON TABLE "FERREDB"."TBL_VENTAS"  IS 'Esta Tabla lleva control de las transacciones de ventas o salidas de la bodega';
--------------------------------------------------------
--  DDL for View LISTAR_CATEGORIAS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FERREDB"."LISTAR_CATEGORIAS" ("ID_CATEGORIA", "CATEGORIA", "DESCRIPCION", "ESTADO") AS 
  SELECT "ID_CATEGORIA","CATEGORIA","DESCRIPCION","ESTADO"
    FROM TBL_CATEGORIA
ORDER BY ID_CATEGORIA;
--------------------------------------------------------
--  DDL for View LISTAR_MONEDAS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FERREDB"."LISTAR_MONEDAS" ("ID_MONEDA", "COD_MONEDA", "DESCRIPCION") AS 
  SELECT "ID_MONEDA", "COD_MONEDA", "DESCRIPCION"
    FROM TBL_MONEDAS
ORDER BY ID_MONEDA;
--------------------------------------------------------
--  DDL for View LISTAR_PROVINCIAS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FERREDB"."LISTAR_PROVINCIAS" ("ID_PROVINCIA", "PROVINCIA") AS 
  SELECT "ID_PROVINCIA","PROVINCIA"
FROM TBL_PROVINCIAS
ORDER BY ID_PROVINCIA;
--------------------------------------------------------
--  DDL for View LISTAR_TBL_TIPO_CIA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FERREDB"."LISTAR_TBL_TIPO_CIA" ("ID_TIPO_CIA", "TIPO_EMPRESA", "DESCRIPCION") AS 
  SELECT ID_TIPO_CIA, TIPO_EMPRESA ,DESCRIPCION
FROM TBL_TIPO_CIA
ORDER BY ID_TIPO_CIA;
--------------------------------------------------------
--  DDL for View LISTAR_UND_MEDIDA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FERREDB"."LISTAR_UND_MEDIDA" ("ID_UND_MEDIDA", "COD_MEDIDA", "DESCRIPCION") AS 
  SELECT "ID_UND_MEDIDA", "COD_MEDIDA", "DESCRIPCION"
    FROM TBL_UND_MED
ORDER BY ID_UND_MEDIDA;
REM INSERTING into FERREDB.TBL_BODEGAS
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_CATEGORIA
SET DEFINE OFF;
Insert into FERREDB.TBL_CATEGORIA (ID_CATEGORIA,CATEGORIA,DESCRIPCION,ESTADO) values ('1','HERRAMIENTAS MANUALES','HERRAMIENTAS QUE NO UTILIZAN ENERGÍA ELECTRICA.','ACTIVO');
Insert into FERREDB.TBL_CATEGORIA (ID_CATEGORIA,CATEGORIA,DESCRIPCION,ESTADO) values ('2','MATERIALES CONTRUCCIONES','MATERIALES PARA OBRA GRIS','ACTIVO');
REM INSERTING into FERREDB.TBL_CLIENT_PROV
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_DETALLE_DEV
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_DETALLE_VENTA
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_EMPRESA
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_INGRESOS_DEV
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_INVENTARIO_ARTICULOS
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_MONEDAS
SET DEFINE OFF;
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('2','AFN','Afgani afgano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('3','ALL','Lek albano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('1','AED','Dirham de los Emiratos Árabes Unidos');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('4','AMD','Dram armenio');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('5','ANG','Florín de las Antillas Holandesas');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('6','AOA','Kwanza angoleño');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('7','ARS','Peso argentino');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('8','AUD','Dólar australiano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('9','AWG','Florín arubeño');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('10','AZM','Manat azerbaiyano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('11','BAM','marco convertible de Bosnia-Herzegovina');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('12','BBD','Dólar de Barbados');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('13','BDT','Taka de Bangladesh');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('14','BGN','Lev búlgaro');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('15','BHD','Dinar bahreiní');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('16','BIF','Franco burundés');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('17','BMD','Dólar de Bermuda');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('18','BND','Dólar de Brunei');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('19','BOB','Boliviano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('20','BOV','Mvdol boliviano (código de fondos)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('21','BRL','Real brasileño');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('22','BSD','Dólar bahameño');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('23','BTN','Ngultrum de Bután');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('24','BWP','Pula de Botswana');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('25','BYR','Rublo bielorruso');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('26','BZD','Dólar de Belice');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('27','CAD','Dólar canadiense');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('28','CDF','Franco congoleño');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('29','CHF','Franco suizo');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('30','CLF','Unidades de fomento chilenas (código de fondos)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('31','CLP','Peso chileno');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('32','CNY','Yuan Renminbi de China');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('33','COP','Peso colombiano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('34','COU','Unidad de valor real colombiana (añadida al COP)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('35','CRC','Colón costarricense');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('36','CSD','Dinar serbio (It was replaced by RSD on October 25, 2006)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('37','CUP','Peso cubano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('38','CVE','Escudo caboverdiano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('39','CYP','Libra chipriota');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('40','CZK','Koruna checo');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('41','DJF','Franco yibutiano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('42','DKK','Corona danesa');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('43','DOP','Peso dominicano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('44','DZD','Dinar algerino');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('45','EEK','Corona estonia');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('46','EGP','Libra egipcia');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('47','ERN','Nakfa eritreo');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('48','ETB','Birr etíope');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('49','EUR','Euro');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('50','FJD','Dólar fijiano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('51','FKP','Libra malvinense');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('52','GBP','Libra esterlina (libra de Gran Bretaña)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('53','GEL','Lari georgiano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('54','GHC','Cedi ghanés');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('55','GIP','Libra de Gibraltar');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('56','GMD','Dalasi gambiano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('57','GNF','Franco guineano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('58','GTQ','Quetzal guatemalteco');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('59','GYD','Dólar guyanés');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('60','HKD','Dólar de Hong Kong');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('61','HNL','Lempira hondureño');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('62','HRK','Kuna croata');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('63','HTG','Gourde haitiano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('64','HUF','Forint húngaro');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('65','IDR','Rupiah indonesia');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('66','ILS','Nuevo shequel israelí');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('67','INR','Rupia india');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('68','IQD','Dinar iraqí');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('69','IRR','Rial iraní');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('70','ISK','Króna islandesa');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('71','JMD','Dólar jamaicano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('72','JOD','Dinar jordano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('73','JPY','Yen japonés');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('74','KES','Chelín keniata');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('75','KGS','Som kirguís (de Kirguistán)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('76','KHR','Riel camboyano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('77','KMF','Franco comoriano (de Comoras)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('78','KPW','Won norcoreano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('79','KRW','Won surcoreano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('80','KWD','Dinar kuwaití');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('81','KYD','Dólar caimano (de Islas Caimán)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('82','KZT','Tenge kazajo (de Kazajstán)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('83','LAK','Kip lao');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('84','LBP','Libra libanesa');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('85','LKR','Rupia de Sri Lanka');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('86','LRD','Dólar liberiano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('87','LSL','Loti lesothense (de Lesotho)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('88','LTL','Litas lituano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('89','LVL','Lat letón');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('90','LYD','Dinar libio');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('91','MAD','Dirham marroquí');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('92','MDL','Leu moldavo');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('93','MGA','Ariary malgache (de Madagascar)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('94','MKD','Denar macedonio');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('95','MMK','Kyat myanmaro');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('96','MNT','Tughrik mongol');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('97','MOP','Pataca de Macao');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('98','MRO','Ouguiya mauritana');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('99','MTL','Lira maltesa');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('100','MUR','Rupia mauricia');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('101','MVR','Rufiyaa maldiva');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('102','MWK','Kwacha malawiano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('103','MXN','Peso mexicano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('104','MXV','Unidad de Inversión (UDI) mexicana (código de fondos)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('105','MYR','Ringgit malayo');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('106','MZM','Metical mozambiqueño');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('107','NAD','Dólar namibio');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('108','NGN','Naira nigeriana');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('109','NIO','Córdoba nicaragüense');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('110','NOK','Corona noruega');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('111','NPR','Rupia nepalesa');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('112','NZD','Dólar neozelandés');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('113','OMR','Rial omaní (de Omán)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('114','PAB','Balboa panameña');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('115','PEN','Nuevo sol peruano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('116','PGK','Kina de Papúa Nueva Guinea');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('117','PHP','Peso filipino');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('118','PKR','Rupia pakistaní');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('119','PLN','zloty polaco');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('120','PYG','Guaraní paraguayo');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('121','QAR','Rial qatarí');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('122','RON','Leu rumano (desde el 1 de julio de 2005)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('123','RUB','Rublo ruso');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('124','RWF','Franco ruandés');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('125','SAR','Riyal saudí');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('126','SBD','Dólar de las Islas Salomón');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('127','SCR','Rupia de Seychelles');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('128','SDD','Dinar sudanés');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('129','SEK','Corona sueca');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('130','SGD','Dólar de Singapur');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('131','SHP','Libra de Santa Helena');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('132','SKK','Corona eslovaca');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('133','SLL','Leone de Sierra Leona');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('134','SOS','Chelín somalí');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('135','SRD','Dólar surinamés (desde el 1 de enero de 2004)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('136','STD','Dobra de Santo Tomé y Príncipe');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('137','SYP','Libra siria');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('138','SZL','Lilangeni suazi (de Suazilandia)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('139','THB','Baht tailandés');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('140','TJS','Somoni tayik (de Tayikistán)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('141','TMM','Manat turcomano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('142','TND','Dinar tunecino');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('143','TOP','Pa’anga tongano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('144','TRY','Nueva lira turca');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('145','TTD','Dólar de Trinidad y Tobago');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('146','TWD','Dólar taiwanés');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('147','TZS','Chelín tanzano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('148','UAH','Hryvnia ucraniana');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('149','UGX','Chelín ugandés');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('150','USD','Dólar estadounidense');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('151','USN','Dólar estadounidense (Siguiente día) (código de fondos)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('152','USS','United States dollar (Mismo día) (código de fondos)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('153','UYU','Peso uruguayo');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('154','UZS','Som uzbeco');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('155','VEB','Bolívar venezolano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('156','VEF','Bolívar fuerte venezolano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('157','VND','Dong vietnamita');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('158','VUV','Vatu vanuatense');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('159','WST','Tala samoana');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('160','XAF','Franco CFA');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('161','XAG','Onza de plata');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('162','XAU','Onza de oro');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('163','XBA','European Composite Unit (EURCO) (Bonds market unit)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('164','XBB','European Monetary Unit (E.M.U.-6) (Bonds market unit)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('165','XBC','European Unit of Account 9 (E.U.A.-9) (Bonds market unit)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('166','XBD','European Unit of Account 17 (E.U.A.-17) (Bonds market unit)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('167','XCD','Dólar del Caribe Oriental');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('168','XDR','Special Drawing Rights (FMI)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('169','XFO','Franco de oro (Special settlement currency)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('170','XFU','Franco UIC (Special settlement currency)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('171','XOF','Franco CFA');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('172','XPD','Onza de paladio');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('173','XPF','Franco CFP');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('174','XPT','Onza de platino');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('175','XTS','Reservado para pruebas');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('176','XXX','Sin divisa');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('177','YER','Rial yemení (de Yemen)');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('178','ZAR','Rand sudafricano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('179','ZMK','Kwacha zambiano');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('180','ZWD','Dólar zimbabuense');
REM INSERTING into FERREDB.TBL_PERMISOS_USUARIOS
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_PROVINCIAS
SET DEFINE OFF;
Insert into FERREDB.TBL_PROVINCIAS (ID_PROVINCIA,PROVINCIA) values ('1','SAN JOSE');
Insert into FERREDB.TBL_PROVINCIAS (ID_PROVINCIA,PROVINCIA) values ('2','ALAJUELA');
Insert into FERREDB.TBL_PROVINCIAS (ID_PROVINCIA,PROVINCIA) values ('3','CARTAGO');
Insert into FERREDB.TBL_PROVINCIAS (ID_PROVINCIA,PROVINCIA) values ('4','HEREDIA');
Insert into FERREDB.TBL_PROVINCIAS (ID_PROVINCIA,PROVINCIA) values ('5','GUANACASTE');
Insert into FERREDB.TBL_PROVINCIAS (ID_PROVINCIA,PROVINCIA) values ('6','PUNTARENAS');
Insert into FERREDB.TBL_PROVINCIAS (ID_PROVINCIA,PROVINCIA) values ('7','LIMON');
REM INSERTING into FERREDB.TBL_TIPO_CAMBIO
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_TIPO_CIA
SET DEFINE OFF;
Insert into FERREDB.TBL_TIPO_CIA (ID_TIPO_CIA,TIPO_EMPRESA,DESCRIPCION) values ('1','OFICINAS CENTRALES','OFICINAS CENTRALES DE LA COPORACION.');
REM INSERTING into FERREDB.TBL_TIPO_IDENTIFICACION
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_TIPO_PERSONERIA
SET DEFINE OFF;
Insert into FERREDB.TBL_TIPO_PERSONERIA (ID_TIPO_PERSONERIA,PERSONERIA) values ('1','FISICA');
Insert into FERREDB.TBL_TIPO_PERSONERIA (ID_TIPO_PERSONERIA,PERSONERIA) values ('2','JURIDIDICA');
Insert into FERREDB.TBL_TIPO_PERSONERIA (ID_TIPO_PERSONERIA,PERSONERIA) values ('3','RESIDENTE');
Insert into FERREDB.TBL_TIPO_PERSONERIA (ID_TIPO_PERSONERIA,PERSONERIA) values ('4','EXTRANJERO');
Insert into FERREDB.TBL_TIPO_PERSONERIA (ID_TIPO_PERSONERIA,PERSONERIA) values ('5','INDOCUMENTADO');
Insert into FERREDB.TBL_TIPO_PERSONERIA (ID_TIPO_PERSONERIA,PERSONERIA) values ('6','OTRO');
REM INSERTING into FERREDB.TBL_TIPO_RELACION
SET DEFINE OFF;
Insert into FERREDB.TBL_TIPO_RELACION (ID_TIPO_RELACION,RELACION) values ('1','CLIENTE');
Insert into FERREDB.TBL_TIPO_RELACION (ID_TIPO_RELACION,RELACION) values ('2','PROVEEDOR');
REM INSERTING into FERREDB.TBL_UND_MED
SET DEFINE OFF;
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('1','Sp','Servicios Profesionales');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('2','m','Metro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('3','kg','Kilogramo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('4','s','Segundo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('5','A','Ampere');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('6','K','Kelvin');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('7','mol','Mol');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('8','cd','Candela');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('9','m²','metro cuadrado');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('10','m³','metro cúbico');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('11','m/s','metro por segundo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('12','m/s²','metro por segundo cuadrado');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('13','1/m','1 por metro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('14','kg/m³','kilogramo por metro cúbico');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('15','A/m²','ampere por metro cuadrado');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('16','A/m','ampere por metro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('17','mol/m³','mol por metro cúbico');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('18','cd/m²','candela por metro cuadrado');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('19','1','uno (indice de refracción)');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('20','rad','radián');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('21','sr','estereorradián');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('22','Hz','hertz');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('23','N','newton');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('24','Pa','pascal');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('25','J','Joule');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('26','W','Watt');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('27','C','coulomb');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('28','V','volt');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('29','F','farad');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('30','?','ohm');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('31','S','siemens');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('32','Wb','weber');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('33','T','tesla');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('34','H','henry');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('35','°C','grado Celsius');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('36','lm','lumen');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('37','lx','lux');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('38','Bq','Becquerel');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('39','Gy','gray');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('40','Sv','sievert');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('41','kat','katal');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('42','Pa·s','pascal segundo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('43','N·m','newton metro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('44','N/m','newton por metro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('45','rad/s','radián por segundo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('46','rad/s²','radián por segundo cuadrado');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('47','W/m²','watt por metro cuadrado');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('48','J/K','joule por kelvin');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('49','J/(kg·K)','joule por kilogramo kelvin');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('50','J/kg','joule por kilogramo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('51','W/(m·K)','watt por metro kevin');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('52','J/m³','joule por metro cúbico');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('53','V/m','volt por metro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('54','C/m³','coulomb por metro cúbico');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('55','C/m²','coulomb por metro cuadrado');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('56','F/m','farad por metro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('57','H/m','henry por metro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('58','J/mol','joule por mol');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('59','J/(mol·K)','joule por mol kelvin');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('60','C/kg','coulomb por kilogramo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('61','Gy/s','gray por segundo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('62','W/sr','watt por estereorradián');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('63','W/(m²·sr)','watt por metro cuadrado estereorradián');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('64','kat/m³','katal por metro cúbico');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('65','min','minuto');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('66','h','hora');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('67','d','día');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('68','º','grado');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('69','´','minuto');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('70','´´','segundo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('71','L','litro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('72','t','tonelada');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('73','Np','neper');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('74','B','bel');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('75','eV','electronvolt');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('76','u','unidad de masa atómica unificada');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('77','ua','unidad astronómica');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('78','Unid','Unidad');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('79','Gal','Galón');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('80','g','Gramo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('81','Km','Kilometro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('82','ln','pulgada');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('83','cm','centimetro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('84','mL','mililitro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('85','mm','Milimetro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('86','Oz','Onzas');
REM INSERTING into FERREDB.TBL_USUARIOS
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_VENTAS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_TBL_EMPRESA
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_EMPRESA" ON "FERREDB"."TBL_EMPRESA" ("ID_CIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_PERMISOS_USUARIOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_PERMISOS_USUARIOS" ON "FERREDB"."TBL_PERMISOS_USUARIOS" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_VENTAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_VENTAS" ON "FERREDB"."TBL_VENTAS" ("ID_VENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_CATEGORIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_CATEGORIA" ON "FERREDB"."TBL_CATEGORIA" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_TIPO_PERSONERIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_TIPO_PERSONERIA" ON "FERREDB"."TBL_TIPO_PERSONERIA" ("ID_TIPO_PERSONERIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_DETALLE_DEV
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_DETALLE_DEV" ON "FERREDB"."TBL_DETALLE_DEV" ("ID_ING_DEV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_UND_MED
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_UND_MED" ON "FERREDB"."TBL_UND_MED" ("ID_UND_MEDIDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_CLIENT_PROV
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_CLIENT_PROV" ON "FERREDB"."TBL_CLIENT_PROV" ("ID_CLI_PROV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_USUARIOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_USUARIOS" ON "FERREDB"."TBL_USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_MONEDAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_MONEDAS" ON "FERREDB"."TBL_MONEDAS" ("ID_MONEDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_INVENTARIO_ARTICULOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_INVENTARIO_ARTICULOS" ON "FERREDB"."TBL_INVENTARIO_ARTICULOS" ("ID_ARTICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_INGRESOS_DEV
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_INGRESOS_DEV" ON "FERREDB"."TBL_INGRESOS_DEV" ("ID_INGRESO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_TIPO_CIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_TIPO_CIA" ON "FERREDB"."TBL_TIPO_CIA" ("ID_TIPO_CIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_PROVINCIAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_PROVINCIAS" ON "FERREDB"."TBL_PROVINCIAS" ("ID_PROVINCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_TIPO_RELACION
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_TIPO_RELACION" ON "FERREDB"."TBL_TIPO_RELACION" ("ID_TIPO_RELACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_TIPO_IDENTIFICACION
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_TIPO_IDENTIFICACION" ON "FERREDB"."TBL_TIPO_IDENTIFICACION" ("ID_TIPO_IDENTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  Constraints for Table TBL_MONEDAS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_MONEDAS" MODIFY ("ID_MONEDA" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_MONEDAS" ADD CONSTRAINT "PK_TBL_MONEDAS" PRIMARY KEY ("ID_MONEDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_DETALLE_VENTA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_DETALLE_VENTA" MODIFY ("ID_DETALLE_VENTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_BODEGAS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_BODEGAS" MODIFY ("ID_BODEGA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_CIA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_TIPO_CIA" MODIFY ("ID_TIPO_CIA" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_TIPO_CIA" ADD CONSTRAINT "PK_TBL_TIPO_CIA" PRIMARY KEY ("ID_TIPO_CIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CATEGORIA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_CATEGORIA" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_CATEGORIA" ADD CONSTRAINT "PK_TBL_CATEGORIA" PRIMARY KEY ("ID_CATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_PERMISOS_USUARIOS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_PERMISOS_USUARIOS" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_PERMISOS_USUARIOS" ADD CONSTRAINT "PK_TBL_PERMISOS_USUARIOS" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_EMPRESA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_EMPRESA" MODIFY ("ID_CIA" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_EMPRESA" ADD CONSTRAINT "PK_TBL_EMPRESA" PRIMARY KEY ("ID_CIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_INVENTARIO_ARTICULOS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_INVENTARIO_ARTICULOS" MODIFY ("ID_ARTICULO" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_INVENTARIO_ARTICULOS" ADD CONSTRAINT "PK_TBL_INVENTARIO_ARTICULOS" PRIMARY KEY ("ID_ARTICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_DETALLE_DEV
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_DETALLE_DEV" MODIFY ("ID_ING_DEV" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_DETALLE_DEV" ADD CONSTRAINT "PK_TBL_DETALLE_DEV" PRIMARY KEY ("ID_ING_DEV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_PERSONERIA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_TIPO_PERSONERIA" ADD CONSTRAINT "PK_TBL_TIPO_PERSONERIA" PRIMARY KEY ("ID_TIPO_PERSONERIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_TIPO_PERSONERIA" MODIFY ("ID_TIPO_PERSONERIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_RELACION
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_TIPO_RELACION" ADD CONSTRAINT "PK_TBL_TIPO_RELACION" PRIMARY KEY ("ID_TIPO_RELACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_TIPO_RELACION" MODIFY ("ID_TIPO_RELACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_INGRESOS_DEV
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_INGRESOS_DEV" MODIFY ("ID_INGRESO" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_INGRESOS_DEV" ADD CONSTRAINT "PK_TBL_INGRESOS_DEV" PRIMARY KEY ("ID_INGRESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_USUARIOS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_USUARIOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_USUARIOS" ADD CONSTRAINT "PK_TBL_USUARIOS" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CLIENT_PROV
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_CLIENT_PROV" MODIFY ("ID_CLI_PROV" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_CLIENT_PROV" ADD CONSTRAINT "PK_TBL_CLIENT_PROV" PRIMARY KEY ("ID_CLI_PROV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_VENTAS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_VENTAS" MODIFY ("ID_VENTA" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_VENTAS" ADD CONSTRAINT "PK_TBL_VENTAS" PRIMARY KEY ("ID_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_PROVINCIAS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_PROVINCIAS" MODIFY ("ID_PROVINCIA" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_PROVINCIAS" ADD CONSTRAINT "PK_TBL_PROVINCIAS" PRIMARY KEY ("ID_PROVINCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_IDENTIFICACION
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_TIPO_IDENTIFICACION" MODIFY ("ID_TIPO_IDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_TIPO_IDENTIFICACION" ADD CONSTRAINT "PK_TBL_TIPO_IDENTIFICACION" PRIMARY KEY ("ID_TIPO_IDENTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_UND_MED
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_UND_MED" MODIFY ("ID_UND_MEDIDA" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_UND_MED" ADD CONSTRAINT "PK_TBL_UND_MED" PRIMARY KEY ("ID_UND_MEDIDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_BODEGAS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_BODEGAS" ADD CONSTRAINT "FK_TBL_BODE_REF_BOD_D_TBL_INGR" FOREIGN KEY ("ID_INGRESO")
	  REFERENCES "FERREDB"."TBL_INGRESOS_DEV" ("ID_INGRESO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FERREDB"."TBL_BODEGAS" ADD CONSTRAINT "FK_TBL_BODE_REF_EMP_B_TBL_EMPR" FOREIGN KEY ("ID_CIA")
	  REFERENCES "FERREDB"."TBL_EMPRESA" ("ID_CIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_CLIENT_PROV
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_CLIENT_PROV" ADD CONSTRAINT "FK_TBL_CLIE_REF_EMP_C_TBL_EMPR" FOREIGN KEY ("ID_CIA")
	  REFERENCES "FERREDB"."TBL_EMPRESA" ("ID_CIA") ENABLE;
  ALTER TABLE "FERREDB"."TBL_CLIENT_PROV" ADD CONSTRAINT "FK_TBL_CLIE_REF_PERSO_TBL_TIPO" FOREIGN KEY ("ID_TIPO_IDENTIFICACION")
	  REFERENCES "FERREDB"."TBL_TIPO_IDENTIFICACION" ("ID_TIPO_IDENTIFICACION") ENABLE;
  ALTER TABLE "FERREDB"."TBL_CLIENT_PROV" ADD CONSTRAINT "FK_TBL_CLIE_REF_PROV__TBL_PROV" FOREIGN KEY ("ID_PROVINCIA")
	  REFERENCES "FERREDB"."TBL_PROVINCIAS" ("ID_PROVINCIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_EMPRESA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_EMPRESA" ADD CONSTRAINT "FK_TBL_EMPR_REF_CIA_E_TBL_TIPO" FOREIGN KEY ("ID_TIPO_CIA")
	  REFERENCES "FERREDB"."TBL_TIPO_CIA" ("ID_TIPO_CIA") ENABLE;
  ALTER TABLE "FERREDB"."TBL_EMPRESA" ADD CONSTRAINT "FK_TBL_EMPR_REF_EMPRE_TBL_PROV" FOREIGN KEY ("ID_PROVINCIA")
	  REFERENCES "FERREDB"."TBL_PROVINCIAS" ("ID_PROVINCIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_INGRESOS_DEV
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_INGRESOS_DEV" ADD CONSTRAINT "FK_TBL_INGR_REF_DEV_V_TBL_VENT" FOREIGN KEY ("ID_VENTA")
	  REFERENCES "FERREDB"."TBL_VENTAS" ("ID_VENTA") ENABLE;
  ALTER TABLE "FERREDB"."TBL_INGRESOS_DEV" ADD CONSTRAINT "FK_TBL_INGR_REV_DEB_E_TBL_EMPR" FOREIGN KEY ("ID_CIA")
	  REFERENCES "FERREDB"."TBL_EMPRESA" ("ID_CIA") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_INVENTARIO_ARTICULOS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_INVENTARIO_ARTICULOS" ADD CONSTRAINT "FK_TBL_INVE_REF_ART_U_TBL_UND_" FOREIGN KEY ("ID_UND_MEDIDA")
	  REFERENCES "FERREDB"."TBL_UND_MED" ("ID_UND_MEDIDA") ENABLE;
  ALTER TABLE "FERREDB"."TBL_INVENTARIO_ARTICULOS" ADD CONSTRAINT "FK_TBL_INVE_REF_CATEG_TBL_CATE" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "FERREDB"."TBL_CATEGORIA" ("ID_CATEGORIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_TIPO_CAMBIO
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_TIPO_CAMBIO" ADD CONSTRAINT "FK_TBL_TIPO_REF_TC_MO_TBL_MONE" FOREIGN KEY ("ID_MONEDA")
	  REFERENCES "FERREDB"."TBL_MONEDAS" ("ID_MONEDA") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_USUARIOS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_USUARIOS" ADD CONSTRAINT "FK_TBL_USUA_REF_USER__TBL_PERM" FOREIGN KEY ("ID_ROL")
	  REFERENCES "FERREDB"."TBL_PERMISOS_USUARIOS" ("ID_ROL") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_VENTAS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_VENTAS" ADD CONSTRAINT "FK_TBL_VENT_REF_EMPRE_TBL_EMPR" FOREIGN KEY ("ID_CIA")
	  REFERENCES "FERREDB"."TBL_EMPRESA" ("ID_CIA") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FERREDB"."TBL_VENTAS" ADD CONSTRAINT "FK_TBL_VENT_REF_USER__TBL_USUA" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "FERREDB"."TBL_USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  DDL for Function EXISTE_PROV
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "FERREDB"."EXISTE_PROV" (PROV IN TBL_PROVINCIAS.PROVINCIA%TYPE)
RETURN BOOLEAN IS

FLAG NUMBER;
BANDERA BOOLEAN := TRUE;
BEGIN
    SELECT COUNT (*)
    INTO FLAG
    FROM TBL_PROVINCIAS
    WHERE PROVINCIA = PROV;
    IF FLAG > 0 THEN
      BANDERA :=  TRUE;
    ELSE
      BANDERA := FALSE;
    END IF;
    RETURN BANDERA;
END;

/
--------------------------------------------------------
--  DDL for Package PDTYPES
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "FERREDB"."PDTYPES" 
as
    TYPE ref_cursor IS REF CURSOR;
end;

-- Integrity package declaration
create or replace package IntegrityPackage AS
 procedure InitNestLevel;
 function GetNestLevel return number;
 procedure NextNestLevel;
 procedure PreviousNestLevel;
 end IntegrityPackage;

/
--------------------------------------------------------
--  DDL for Package Body INTEGRITYPACKAGE
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "FERREDB"."INTEGRITYPACKAGE" AS
 NestLevel number;

-- Procedure to initialize the trigger nest level
 procedure InitNestLevel is
 begin
 NestLevel := 0;
 end;


-- Function to return the trigger nest level
 function GetNestLevel return number is
 begin
 if NestLevel is null then
     NestLevel := 0;
 end if;
 return(NestLevel);
 end;

-- Procedure to increase the trigger nest level
 procedure NextNestLevel is
 begin
 if NestLevel is null then
     NestLevel := 0;
 end if;
 NestLevel := NestLevel + 1;
 end;

-- Procedure to decrease the trigger nest level
 procedure PreviousNestLevel is
 begin
 NestLevel := NestLevel - 1;
 end;

 end IntegrityPackage;

/
--------------------------------------------------------
--  DDL for Procedure ACTIV_CATEGORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."ACTIV_CATEGORIA" 
(IDCAT IN NUMBER)
AS
VARID number:=IDCAT;
BEGIN
  UPDATE TBL_CATEGORIA 
  SET ESTADO = 'ACTIVO'
  WHERE ID_CATEGORIA = VARID;
END;

/
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_TBL_CATEGORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."ACTUALIZAR_TBL_CATEGORIA" 
(IDCAT IN NUMBER,
CATEGORI IN VARCHAR2,
DESCRIP IN VARCHAR2)
AS 
BEGIN
   UPDATE TBL_CATEGORIA
   SET CATEGORIA = CATEGORI,DESCRIPCION = DESCRIP
   WHERE ID_CATEGORIA = IDCAT;
   COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_TBL_MONEDAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."ACTUALIZAR_TBL_MONEDAS" 
(IDM IN NUMBER,
COD_MON IN VARCHAR2,
DESCRIP IN VARCHAR2)
AS
BEGIN
   UPDATE TBL_MONEDAS
   SET COD_MONEDA = COD_MON,DESCRIPCION = DESCRIP
   WHERE ID_MONEDA = IDM;
   COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_TBL_PROVINCIAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."ACTUALIZAR_TBL_PROVINCIAS" 
(IDPROV IN NUMBER, PROV IN VARCHAR2)
AS
  VARID NUMBER:= IDPROV;
  VARPROV VARCHAR2(20):= PROV;
BEGIN
      UPDATE TBL_PROVINCIAS
      SET PROVINCIA = VARPROV
      WHERE ID_PROVINCIA = VARID;
END ACTUALIZAR_TBL_PROVINCIAS;

/
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_TBL_TIPO_CIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."ACTUALIZAR_TBL_TIPO_CIA" 
(ID_CIA IN NUMBER, TIPO_CIA IN VARCHAR2, DESCRIP IN VARCHAR2)
AS
  VARID NUMBER:= ID_CIA;
  VARTIPOCIA VARCHAR2(20):= TIPO_CIA;
  VARDESCRIP VARCHAR (50):= DESCRIP;
  
BEGIN
      UPDATE TBL_TIPO_CIA
      SET TIPO_EMPRESA = TIPO_CIA, DESCRIPCION = DESCRIP
      WHERE ID_TIPO_CIA = VARID;
END ACTUALIZAR_TBL_TIPO_CIA;

/
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_TBL_UND_MED
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."ACTUALIZAR_TBL_UND_MED" 
(IDMED IN NUMBER,
COD_MED IN VARCHAR2,
DESCRIP IN VARCHAR2)
AS
BEGIN
   UPDATE TBL_UND_MED
   SET COD_MEDIDA = COD_MED,DESCRIPCION = DESCRIP
   WHERE ID_UND_MEDIDA = IDMED;
   COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure BORRAR_TBL_CATEGORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."BORRAR_TBL_CATEGORIA" 
(IDCAT IN NUMBER)
AS 
  VARID number:=IDCAT;
BEGIN
    DELETE FROM TBL_CATEGORIA
    WHERE ID_CATEGORIA = VARID;
END BORRAR_TBL_CATEGORIA;

/
--------------------------------------------------------
--  DDL for Procedure BORRAR_TBL_MONEDAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."BORRAR_TBL_MONEDAS" 
(ID_MON IN NUMBER)
AS 
  VARID number:=ID_MON;
BEGIN
    DELETE FROM TBL_MONEDAS
    WHERE ID_MONEDA = ID_MON;
END BORRAR_TBL_MONEDAS;

/
--------------------------------------------------------
--  DDL for Procedure BORRAR_TBL_PROVINCIAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."BORRAR_TBL_PROVINCIAS" 
(ID_PROV IN NUMBER)
AS 
  VARID number:=ID_PROV;
BEGIN
    DELETE FROM TBL_PROVINCIAS
    WHERE ID_PROVINCIA = VARID;
END BORRAR_TBL_PROVINCIAS;

/
--------------------------------------------------------
--  DDL for Procedure BORRAR_TBL_TIPO_CIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."BORRAR_TBL_TIPO_CIA" 
(ID_CIA IN NUMBER)
AS 
  VARID number:=ID_CIA;
BEGIN
    DELETE FROM TBL_TIPO_CIA
    WHERE ID_TIPO_CIA = VARID;
END BORRAR_TBL_TIPO_CIA;

/
--------------------------------------------------------
--  DDL for Procedure BORRAR_TBL_UND_MED
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."BORRAR_TBL_UND_MED" 
(ID_MED IN NUMBER)
AS 
  VARID number:=ID_MED;
BEGIN
    DELETE FROM TBL_UND_MED
    WHERE ID_UND_MEDIDA = ID_MED;
END BORRAR_TBL_UND_MED;

/
--------------------------------------------------------
--  DDL for Procedure BUSCAR_TBL_CATEGORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."BUSCAR_TBL_CATEGORIA" 
(CATEGOR IN TBL_CATEGORIA.CATEGORIA%TYPE, 
REGISTROS OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN REGISTROS FOR SELECT ID_CATEGORIA,CATEGORIA, DESCRIPCION, ESTADO
    FROM TBL_CATEGORIA
    WHERE CATEGORIA LIKE '%' ||CATEGOR|| '%'
    ORDER BY ID_CATEGORIA;
END BUSCAR_TBL_CATEGORIA;

/
--------------------------------------------------------
--  DDL for Procedure BUSCAR_TBL_MONEDAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."BUSCAR_TBL_MONEDAS" 
(MON IN TBL_MONEDAS.DESCRIPCION%TYPE, 
REGISTROS OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN REGISTROS FOR SELECT ID_MONEDA,COD_MONEDA, DESCRIPCION
    FROM TBL_MONEDAS
    WHERE DESCRIPCION LIKE '%' ||MON|| '%'
    ORDER BY ID_MONEDA;
END BUSCAR_TBL_MONEDAS;

/
--------------------------------------------------------
--  DDL for Procedure BUSCAR_TBL_PROVINCIAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."BUSCAR_TBL_PROVINCIAS" 
(PROV IN TBL_PROVINCIAS.PROVINCIA%TYPE, 
REGISTROS OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN REGISTROS FOR SELECT ID_PROVINCIA,PROVINCIA 
    FROM TBL_PROVINCIAS
    WHERE PROVINCIA LIKE '%' ||PROV|| '%'
    ORDER BY ID_PROVINCIA;
END BUSCAR_TBL_PROVINCIAS;

/
--------------------------------------------------------
--  DDL for Procedure BUSCAR_TBL_TIPO_CIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."BUSCAR_TBL_TIPO_CIA" 
(TIPOEM IN TBL_TIPO_CIA.TIPO_EMPRESA%TYPE, 
REGISTROS OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN REGISTROS FOR SELECT ID_TIPO_CIA,TIPO_EMPRESA, DESCRIPCION
    FROM TBL_TIPO_CIA
    WHERE TIPO_EMPRESA LIKE '%' ||TIPOEM|| '%'
    ORDER BY ID_TIPO_CIA;
END BUSCAR_TBL_TIPO_CIA;

/
--------------------------------------------------------
--  DDL for Procedure BUSCAR_TBL_UND_MEDIDAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."BUSCAR_TBL_UND_MEDIDAS" 
(MED IN TBL_UND_MED.DESCRIPCION%TYPE, 
REGISTROS OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN REGISTROS FOR SELECT ID_UND_MEDIDA, COD_MEDIDA, DESCRIPCION
    FROM TBL_UND_MED
    WHERE DESCRIPCION LIKE '%' ||MED|| '%'
    ORDER BY ID_UND_MEDIDA;
END BUSCAR_TBL_UND_MEDIDAS;

/
--------------------------------------------------------
--  DDL for Procedure DESACTIV_CATEGORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."DESACTIV_CATEGORIA" 
(IDCAT IN NUMBER)
AS
VARID number:=IDCAT;
BEGIN
  UPDATE TBL_CATEGORIA 
  SET ESTADO = 'INACTIVO'
  WHERE ID_CATEGORIA = VARID;
END;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_TBL_CATEGORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."INSERTAR_TBL_CATEGORIA" 
(IDCAT IN NUMBER,
CATEGORI IN VARCHAR2,
DESCRIP IN VARCHAR2)
AS 
BEGIN
    INSERT INTO TBL_CATEGORIA(ID_CATEGORIA, CATEGORIA, DESCRIPCION)
    VALUES (IDCAT, CATEGORI,DESCRIP);
    COMMIT;
END INSERTAR_TBL_CATEGORIA;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_TBL_MONEDAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."INSERTAR_TBL_MONEDAS" 
(IDM IN NUMBER,
COD_MON IN VARCHAR2,
DESCRIP IN VARCHAR2)
AS 
BEGIN
    INSERT INTO TBL_MONEDAS(ID_MONEDA, COD_MONEDA, DESCRIPCION)
    VALUES (IDM, COD_MON,DESCRIP);
    COMMIT;
END INSERTAR_TBL_MONEDAS;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_TBL_PROVINCIAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."INSERTAR_TBL_PROVINCIAS" (ID IN NUMBER, NOMB_PROV IN VARCHAR2 )
AS 
BEGIN
    INSERT INTO TBL_PROVINCIAS(ID_PROVINCIA,PROVINCIA)
    VALUES (ID, NOMB_PROV);
    COMMIT;
END INSERTAR_TBL_PROVINCIAS;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_TBL_TIPO_CIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."INSERTAR_TBL_TIPO_CIA" 
(IDEMP IN NUMBER,
TIPO_EMP IN VARCHAR2,
DESCRIP IN VARCHAR2)
AS 
BEGIN
    INSERT INTO TBL_TIPO_CIA(ID_TIPO_CIA,TIPO_EMPRESA,DESCRIPCION)
    VALUES (IDEMP, TIPO_EMP,DESCRIP);
    COMMIT;
END INSERTAR_TBL_TIPO_CIA;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_TBL_UND_MED
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."INSERTAR_TBL_UND_MED" 
(IDMED IN NUMBER,
COD_MED IN VARCHAR2,
DESCRIP IN VARCHAR2)
AS 
BEGIN
    INSERT INTO TBL_UND_MED(ID_UND_MEDIDA, COD_MEDIDA, DESCRIPCION)
    VALUES (IDMED, COD_MED,DESCRIP);
    COMMIT;
END INSERTAR_TBL_UND_MED;

/
--------------------------------------------------------
--  DDL for Procedure LISTAR_TBL_CATEGORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."LISTAR_TBL_CATEGORIA" 
(REGISTROS OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN REGISTROS FOR SELECT * 
  FROM LISTAR_CATEGORIAS;
END LISTAR_TBL_CATEGORIA;

/
--------------------------------------------------------
--  DDL for Procedure LISTAR_TBL_MONEDAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."LISTAR_TBL_MONEDAS" (REGISTROS OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN REGISTROS FOR SELECT * FROM LISTAR_MONEDAS;
END LISTAR_TBL_MONEDAS;

/
--------------------------------------------------------
--  DDL for Procedure LISTAR_TBL_PROVINCIAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."LISTAR_TBL_PROVINCIAS" (REGISTROS OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN REGISTROS FOR SELECT * FROM LISTAR_PROVINCIAS;
END LISTAR_TBL_PROVINCIAS;

/*SET AUTOPRINT ON;

VARIABLE MEMORIA SYS_REFCURSOR;
EXECUTE LISTARPROV(:MEMORIA);*/

/
--------------------------------------------------------
--  DDL for Procedure LISTAR_TIPO_CIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."LISTAR_TIPO_CIA" (REGISTROS OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN REGISTROS FOR SELECT * FROM LISTAR_TBL_TIPO_CIA;
END LISTAR_TIPO_CIA;

/
--------------------------------------------------------
--  DDL for Procedure LISTAR_UNIDADES_MEDIDA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."LISTAR_UNIDADES_MEDIDA" (REGISTROS OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN REGISTROS FOR SELECT * FROM LISTAR_UND_MEDIDA;
END LISTAR_UNIDADES_MEDIDA;

/
