--------------------------------------------------------
-- Archivo creado  - lunes-julio-06-2020   
--------------------------------------------------------
DROP TABLE "FERREDB"."TBL_BODEGAS" cascade constraints;
DROP TABLE "FERREDB"."TBL_CATEGORIA" cascade constraints;
DROP TABLE "FERREDB"."TBL_CLIENT_PROV" cascade constraints;
DROP TABLE "FERREDB"."TBL_DETALLE_DEV" cascade constraints;
DROP TABLE "FERREDB"."TBL_DETALLE_VENTA" cascade constraints;
DROP TABLE "FERREDB"."TBL_EMPRESA" cascade constraints;
DROP TABLE "FERREDB"."TBL_INGRESOS_DEV" cascade constraints;
DROP TABLE "FERREDB"."TBL_INVENTARIO_ARTICULOS" cascade constraints;
DROP TABLE "FERREDB"."TBL_MONEDAS" cascade constraints;
DROP TABLE "FERREDB"."TBL_PERMISOS_USUARIOS" cascade constraints;
DROP TABLE "FERREDB"."TBL_PROVINCIAS" cascade constraints;
DROP TABLE "FERREDB"."TBL_TIPO_CAMBIO" cascade constraints;
DROP TABLE "FERREDB"."TBL_TIPO_CIA" cascade constraints;
DROP TABLE "FERREDB"."TBL_TIPO_IDENTIFICACION" cascade constraints;
DROP TABLE "FERREDB"."TBL_TIPO_PERSONERIA" cascade constraints;
DROP TABLE "FERREDB"."TBL_TIPO_RELACION" cascade constraints;
DROP TABLE "FERREDB"."TBL_UND_MED" cascade constraints;
DROP TABLE "FERREDB"."TBL_USUARIOS" cascade constraints;
DROP TABLE "FERREDB"."TBL_VENTAS" cascade constraints;
DROP SEQUENCE "FERREDB"."SEC_ID_ARTICULO";
DROP SEQUENCE "FERREDB"."SECIDPROV";
DROP SEQUENCE "FERREDB"."SEC_ID_PROV_TBL_PROVINCIAS";
DROP VIEW "FERREDB"."LISTAR_PROVINCIAS";
DROP VIEW "FERREDB"."LISTAR_TBL_TIPO_CIA";
DROP FUNCTION "FERREDB"."EXISTE_PROV";
DROP PROCEDURE "FERREDB"."ACTUALIZAR_TBL_PROVINCIAS";
DROP PROCEDURE "FERREDB"."BORRAR_TBL_PROVINCIAS";
DROP PROCEDURE "FERREDB"."BUSCAR_TBL_PROVINCIAS";
DROP PROCEDURE "FERREDB"."INSERTAR_TBL_PROVINCIAS";
DROP PROCEDURE "FERREDB"."INSERTAR_TBL_TIPO_CIA";
DROP PROCEDURE "FERREDB"."LISTAR_TBL_PROVINCIAS";
DROP PROCEDURE "FERREDB"."LISTAR_TIPO_CIA";
--------------------------------------------------------
--  DDL for Sequence SEC_ID_ARTICULO
--------------------------------------------------------

   CREATE SEQUENCE  "FERREDB"."SEC_ID_ARTICULO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SECIDPROV
--------------------------------------------------------

   CREATE SEQUENCE  "FERREDB"."SECIDPROV"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_ID_PROV_TBL_PROVINCIAS
--------------------------------------------------------

   CREATE SEQUENCE  "FERREDB"."SEC_ID_PROV_TBL_PROVINCIAS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table TBL_BODEGAS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_BODEGAS" 
   (	"ID_CIA" NUMBER(*,0), 
	"ID_BODEGA" NUMBER(*,0), 
	"ID_ARTICULO" NUMBER(*,0), 
	"COD_BODEGA" VARCHAR2(10 BYTE), 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"UBICACION" VARCHAR2(100 BYTE), 
	"STOCK" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_CATEGORIA
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_CATEGORIA" 
   (	"ID_CATEGORIA" NUMBER(*,0), 
	"CATEGORIA" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_CLIENT_PROV
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_CLIENT_PROV" 
   (	"ID_CIA" NUMBER(*,0), 
	"ID_CLI_PROV" NUMBER(*,0), 
	"ID_TIPO_IDENTIFICACION" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"NUM_DOC" VARCHAR2(20 BYTE), 
	"ID_PROVINCIA" NUMBER(*,0), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"WEB" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_DETALLE_DEV
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_DETALLE_DEV" 
   (	"ID_ING_DEV" NUMBER(*,0), 
	"ID_INGRESO" NUMBER(*,0), 
	"ID_ARTICULO" NUMBER(*,0), 
	"CANTIDAD" NUMBER(*,0), 
	"PRECIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_DETALLE_VENTA
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_DETALLE_VENTA" 
   (	"ID_DETALLE_VENTA" NUMBER(*,0), 
	"ID_VENTA" NUMBER(*,0), 
	"ID_ARTICULO" NUMBER(*,0), 
	"ID_BODEGA" NUMBER(*,0), 
	"PRECIO" NUMBER(11,2), 
	"DESCUENTO" NUMBER(11,2), 
	"CANTIDAD" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_EMPRESA
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_EMPRESA" 
   (	"ID_CIA" NUMBER(*,0), 
	"ID_TIPO_CIA" NUMBER(*,0), 
	"ID_TIPO_IDENTIFICACION" NUMBER(*,0), 
	"NUM_ID" VARCHAR2(20 BYTE), 
	"RAZON_SOCIAL" VARCHAR2(50 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"ID_PROVINCIA" NUMBER(2,0), 
	"DIRECCION" VARCHAR2(255 BYTE), 
	"TEL1" VARCHAR2(15 BYTE), 
	"TEL2" VARCHAR2(15 BYTE), 
	"FAX" VARCHAR2(15 BYTE), 
	"CP" VARCHAR2(10 BYTE), 
	"WEB" VARCHAR2(60 BYTE), 
	"E_MAIL" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_INGRESOS_DEV
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_INGRESOS_DEV" 
   (	"ID_INGRESO" NUMBER(*,0), 
	"ID_CIA" NUMBER(*,0), 
	"ID_CLI_PROV" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"TIPO_COMPROBANTE" VARCHAR2(20 BYTE), 
	"CONSECUTIVO" NUMBER(*,0), 
	"FECHA" DATE, 
	"IMPUESTO" NUMBER(11,2), 
	"TOTAL" NUMBER(11,2), 
	"ESTADO" VARCHAR2(20 BYTE), 
	"ID_BODEGA" NUMBER(*,0), 
	"ID_VENTA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_INVENTARIO_ARTICULOS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_INVENTARIO_ARTICULOS" 
   (	"ID_ARTICULO" NUMBER(*,0), 
	"ID_CATEGORIA" NUMBER(*,0), 
	"ID_BODEGA" NUMBER(*,0), 
	"CODIGO_BARRAS" VARCHAR2(50 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"ID_UND_MEDIDA" NUMBER(*,0), 
	"PRECIO_VENTA" NUMBER(11,2), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"IMAGEN" VARCHAR2(20 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_MONEDAS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_MONEDAS" 
   (	"ID_MONEDA" NUMBER(*,0), 
	"COD_MONEDA" VARCHAR2(10 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_PERMISOS_USUARIOS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_PERMISOS_USUARIOS" 
   (	"ID_ROL" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_PROVINCIAS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_PROVINCIAS" 
   (	"ID_PROVINCIA" NUMBER(*,0), 
	"PROVINCIA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_CAMBIO
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_TIPO_CAMBIO" 
   (	"ID_TC" NUMBER(*,0), 
	"ID_MONEDA" NUMBER(*,0), 
	"COMPRA" NUMBER(*,0), 
	"VENTA" NUMBER(*,0), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_CIA
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_TIPO_CIA" 
   (	"ID_TIPO_CIA" NUMBER(*,0), 
	"TIPO_EMPRESA" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_IDENTIFICACION
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_TIPO_IDENTIFICACION" 
   (	"ID_TIPO_IDENTIFICACION" NUMBER(*,0), 
	"PERSONERIA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_PERSONERIA
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_TIPO_PERSONERIA" 
   (	"ID_TIPO_PERSONERIA" NUMBER(*,0), 
	"PERSONERIA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_RELACION
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_TIPO_RELACION" 
   (	"ID_TIPO_RELACION" NUMBER(*,0), 
	"RELACION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_UND_MED
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_UND_MED" 
   (	"ID_UND_MEDIDA" NUMBER(*,0), 
	"COD_MEDIDA" VARCHAR2(10 BYTE), 
	"DESCRIPCION" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_USUARIOS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_USUARIOS" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"ID_ROL" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO_1" VARCHAR2(50 BYTE), 
	"APELLIDO_2" VARCHAR2(50 BYTE), 
	"ID_TIPO_DOCUMENTO" VARCHAR2(20 BYTE), 
	"NUM_IDENTIFICACION" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(255 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(15 BYTE), 
	"ESTADO" CHAR(1 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_VENTAS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_VENTAS" 
   (	"ID_CIA" NUMBER(*,0), 
	"ID_VENTA" NUMBER(*,0), 
	"ID_DETALLE_VENTA" NUMBER(*,0), 
	"ID_CLIENTE" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"ID_COMPROBANTE" VARCHAR2(10 BYTE), 
	"FECHA" DATE, 
	"HORA" TIMESTAMP (6), 
	"IMPUESTO" NUMBER(10,2), 
	"TOTAL" NUMBER(10,2), 
	"ESTADO" CHAR(1 BYTE), 
	"ID_TC" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;

   COMMENT ON TABLE "FERREDB"."TBL_VENTAS"  IS 'Esta Tabla lleva control de las transacciones de ventas o salidas de la bodega';
--------------------------------------------------------
--  DDL for View LISTAR_PROVINCIAS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FERREDB"."LISTAR_PROVINCIAS" ("ID_PROVINCIA", "PROVINCIA") AS 
  SELECT "ID_PROVINCIA","PROVINCIA"
FROM TBL_PROVINCIAS
ORDER BY ID_PROVINCIA;
--------------------------------------------------------
--  DDL for View LISTAR_TBL_TIPO_CIA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FERREDB"."LISTAR_TBL_TIPO_CIA" ("ID_TIPO_CIA", "TIPO_EMPRESA", "DESCRIPCION") AS 
  SELECT ID_TIPO_CIA, TIPO_EMPRESA ,DESCRIPCION
FROM TBL_TIPO_CIA
ORDER BY ID_TIPO_CIA;
REM INSERTING into FERREDB.TBL_BODEGAS
SET DEFINE OFF;
Insert into FERREDB.TBL_BODEGAS (ID_CIA,ID_BODEGA,ID_ARTICULO,COD_BODEGA,DESCRIPCION,UBICACION,STOCK) values ('1','1','203020','01','BODEGA BPT 01','02','20');
REM INSERTING into FERREDB.TBL_CATEGORIA
SET DEFINE OFF;
Insert into FERREDB.TBL_CATEGORIA (ID_CATEGORIA,CATEGORIA,DESCRIPCION,ESTADO) values ('1','DISCOS DUROS ESTADO SOLIDO','DISCOS DUROS ESTADO SOLIDO','1');
REM INSERTING into FERREDB.TBL_CLIENT_PROV
SET DEFINE OFF;
Insert into FERREDB.TBL_CLIENT_PROV (ID_CIA,ID_CLI_PROV,ID_TIPO_IDENTIFICACION,NOMBRE,NUM_DOC,ID_PROVINCIA,DIRECCION,TELEFONO,EMAIL,WEB) values ('1','1','01','MARCO ANTONIO AGUILAR TORRES','401780287','4','SANTA BARBARA','7012-0624','MAGUILAR@GMAIL.COM','WWW.SOLUCIONES.COM');
REM INSERTING into FERREDB.TBL_DETALLE_DEV
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_DETALLE_VENTA
SET DEFINE OFF;
Insert into FERREDB.TBL_DETALLE_VENTA (ID_DETALLE_VENTA,ID_VENTA,ID_ARTICULO,ID_BODEGA,PRECIO,DESCUENTO,CANTIDAD) values ('1','1','203020','1','35000','0','1');
REM INSERTING into FERREDB.TBL_EMPRESA
SET DEFINE OFF;
Insert into FERREDB.TBL_EMPRESA (ID_CIA,ID_TIPO_CIA,ID_TIPO_IDENTIFICACION,NUM_ID,RAZON_SOCIAL,NOMBRE,ID_PROVINCIA,DIRECCION,TEL1,TEL2,FAX,CP,WEB,E_MAIL) values ('1','1','2','310220202030','MV SOLUCIONES','MV SOLUCIONES','4','SANTA BARBARA','2020-2222','2020-2221','22220-2220','40401','WWW.SOLUCIONES.COM','WWW.SOLUCIONES.COM');
REM INSERTING into FERREDB.TBL_INGRESOS_DEV
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_INVENTARIO_ARTICULOS
SET DEFINE OFF;
Insert into FERREDB.TBL_INVENTARIO_ARTICULOS (ID_ARTICULO,ID_CATEGORIA,ID_BODEGA,CODIGO_BARRAS,NOMBRE,ID_UND_MEDIDA,PRECIO_VENTA,DESCRIPCION,IMAGEN,ESTADO) values ('203020','1','1','7613035199507','DISCO DURO SSD SEGATE 1TB M.2 2220','76','35000','DISCO DURO SSD SEGATE 1TB M.2 2220',null,'1');
REM INSERTING into FERREDB.TBL_MONEDAS
SET DEFINE OFF;
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('1','CRC','COLONES');
Insert into FERREDB.TBL_MONEDAS (ID_MONEDA,COD_MONEDA,DESCRIPCION) values ('2','USD','DOLARES ESTADOUNIDENSES');
REM INSERTING into FERREDB.TBL_PERMISOS_USUARIOS
SET DEFINE OFF;
Insert into FERREDB.TBL_PERMISOS_USUARIOS (ID_ROL,NOMBRE,DESCRIPCION,ESTADO) values ('1','ADMINISTRADOR','ADMINISTRADOR DEL SISTEMA','1');
REM INSERTING into FERREDB.TBL_PROVINCIAS
SET DEFINE OFF;
Insert into FERREDB.TBL_PROVINCIAS (ID_PROVINCIA,PROVINCIA) values ('1','SAN JOSÉ');
Insert into FERREDB.TBL_PROVINCIAS (ID_PROVINCIA,PROVINCIA) values ('2','ALAJUELA');
Insert into FERREDB.TBL_PROVINCIAS (ID_PROVINCIA,PROVINCIA) values ('3','CARTAGO');
Insert into FERREDB.TBL_PROVINCIAS (ID_PROVINCIA,PROVINCIA) values ('4','HEREDIA');
REM INSERTING into FERREDB.TBL_TIPO_CAMBIO
SET DEFINE OFF;
Insert into FERREDB.TBL_TIPO_CAMBIO (ID_TC,ID_MONEDA,COMPRA,VENTA,FECHA) values ('1','1','570','585',to_date('06/07/20','DD/MM/RR'));
REM INSERTING into FERREDB.TBL_TIPO_CIA
SET DEFINE OFF;
Insert into FERREDB.TBL_TIPO_CIA (ID_TIPO_CIA,TIPO_EMPRESA,DESCRIPCION) values ('1','CASA MATRIZ','CASA MATRIS DE LA EMPRESA');
REM INSERTING into FERREDB.TBL_TIPO_IDENTIFICACION
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_TIPO_PERSONERIA
SET DEFINE OFF;
Insert into FERREDB.TBL_TIPO_PERSONERIA (ID_TIPO_PERSONERIA,PERSONERIA) values ('1','FISICA');
Insert into FERREDB.TBL_TIPO_PERSONERIA (ID_TIPO_PERSONERIA,PERSONERIA) values ('2','JURIDIDICA');
Insert into FERREDB.TBL_TIPO_PERSONERIA (ID_TIPO_PERSONERIA,PERSONERIA) values ('3','RESIDENTE');
Insert into FERREDB.TBL_TIPO_PERSONERIA (ID_TIPO_PERSONERIA,PERSONERIA) values ('4','EXTRANJERO');
Insert into FERREDB.TBL_TIPO_PERSONERIA (ID_TIPO_PERSONERIA,PERSONERIA) values ('5','INDOCUMENTADO');
Insert into FERREDB.TBL_TIPO_PERSONERIA (ID_TIPO_PERSONERIA,PERSONERIA) values ('6','OTRO');
REM INSERTING into FERREDB.TBL_TIPO_RELACION
SET DEFINE OFF;
Insert into FERREDB.TBL_TIPO_RELACION (ID_TIPO_RELACION,RELACION) values ('1','CLIENTE');
Insert into FERREDB.TBL_TIPO_RELACION (ID_TIPO_RELACION,RELACION) values ('2','PROVEEDOR');
REM INSERTING into FERREDB.TBL_UND_MED
SET DEFINE OFF;
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('1','Sp','Servicios Profesionales');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('2','m','Metro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('3','kg','Kilogramo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('4','s','Segundo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('5','A','Ampere');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('6','K','Kelvin');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('7','mol','Mol');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('8','cd','Candela');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('9','m²','metro cuadrado');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('10','m³','metro cúbico');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('11','m/s','metro por segundo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('12','m/s²','metro por segundo cuadrado');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('13','1/m','1 por metro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('14','kg/m³','kilogramo por metro cúbico');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('15','A/m²','ampere por metro cuadrado');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('16','A/m','ampere por metro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('17','mol/m³','mol por metro cúbico');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('18','cd/m²','candela por metro cuadrado');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('19','1','uno (indice de refracción)');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('20','rad','radián');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('21','sr','estereorradián');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('22','Hz','hertz');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('23','N','newton');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('24','Pa','pascal');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('25','J','Joule');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('26','W','Watt');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('27','C','coulomb');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('28','V','volt');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('29','F','farad');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('30','?','ohm');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('31','S','siemens');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('32','Wb','weber');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('33','T','tesla');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('34','H','henry');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('35','°C','grado Celsius');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('36','lm','lumen');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('37','lx','lux');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('38','Bq','Becquerel');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('39','Gy','gray');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('40','Sv','sievert');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('41','kat','katal');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('42','Pa·s','pascal segundo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('43','N·m','newton metro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('44','N/m','newton por metro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('45','rad/s','radián por segundo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('46','rad/s²','radián por segundo cuadrado');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('47','W/m²','watt por metro cuadrado');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('48','J/K','joule por kelvin');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('49','J/(kg·K)','joule por kilogramo kelvin');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('50','J/kg','joule por kilogramo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('51','W/(m·K)','watt por metro kevin');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('52','J/m³','joule por metro cúbico');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('53','V/m','volt por metro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('54','C/m³','coulomb por metro cúbico');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('55','C/m²','coulomb por metro cuadrado');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('56','F/m','farad por metro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('57','H/m','henry por metro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('58','J/mol','joule por mol');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('59','J/(mol·K)','joule por mol kelvin');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('60','C/kg','coulomb por kilogramo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('61','Gy/s','gray por segundo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('62','W/sr','watt por estereorradián');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('64','kat/m³','katal por metro cúbico');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('65','min','minuto');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('66','h','hora');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('67','d','día');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('68','º','grado');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('69','´','minuto');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('70','´´','segundo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('71','L','litro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('72','t','tonelada');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('73','Np','neper');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('74','B','bel');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('75','eV','electronvolt');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('76','u','unidad de masa atómica unificada');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('77','ua','unidad astronómica');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('78','Unid','Unidad');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('79','Gal','Galón');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('80','g','Gramo');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('81','Km','Kilometro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('82','ln','pulgada');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('83','cm','centimetro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('84','mL','mililitro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('85','mm','Milimetro');
Insert into FERREDB.TBL_UND_MED (ID_UND_MEDIDA,COD_MEDIDA,DESCRIPCION) values ('86','Oz','Onzas');
REM INSERTING into FERREDB.TBL_USUARIOS
SET DEFINE OFF;
Insert into FERREDB.TBL_USUARIOS (ID_USUARIO,ID_ROL,NOMBRE,APELLIDO_1,APELLIDO_2,ID_TIPO_DOCUMENTO,NUM_IDENTIFICACION,DIRECCION,TELEFONO,EMAIL,PASSWORD,ESTADO,USERNAME) values ('1','1','VANESSA','VIQUEZ','ABARCA','1','205590977','BARVA','2260-0000','VANE@GMAIL.COM','VVANE$1981','1','VVVIQUEZ');
REM INSERTING into FERREDB.TBL_VENTAS
SET DEFINE OFF;
Insert into FERREDB.TBL_VENTAS (ID_CIA,ID_VENTA,ID_DETALLE_VENTA,ID_CLIENTE,ID_USUARIO,ID_COMPROBANTE,FECHA,HORA,IMPUESTO,TOTAL,ESTADO,ID_TC) values ('1','11','1','11','1','1',to_date('06/07/20','DD/MM/RR'),to_timestamp('06/07/20 21:33:30,651000000','DD/MM/RR HH24:MI:SSXFF'),'44450','339550','1','11');
--------------------------------------------------------
--  DDL for Index PK_TBL_EMPRESA
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_EMPRESA" ON "FERREDB"."TBL_EMPRESA" ("ID_CIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_PERMISOS_USUARIOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_PERMISOS_USUARIOS" ON "FERREDB"."TBL_PERMISOS_USUARIOS" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_VENTAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_VENTAS" ON "FERREDB"."TBL_VENTAS" ("ID_VENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_CATEGORIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_CATEGORIA" ON "FERREDB"."TBL_CATEGORIA" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_TIPO_PERSONERIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_TIPO_PERSONERIA" ON "FERREDB"."TBL_TIPO_PERSONERIA" ("ID_TIPO_PERSONERIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_DETALLE_DEV
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_DETALLE_DEV" ON "FERREDB"."TBL_DETALLE_DEV" ("ID_ING_DEV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_UND_MED
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_UND_MED" ON "FERREDB"."TBL_UND_MED" ("ID_UND_MEDIDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_CLIENT_PROV
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_CLIENT_PROV" ON "FERREDB"."TBL_CLIENT_PROV" ("ID_CLI_PROV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_USUARIOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_USUARIOS" ON "FERREDB"."TBL_USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_MONEDAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_MONEDAS" ON "FERREDB"."TBL_MONEDAS" ("ID_MONEDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_BODEGAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_BODEGAS" ON "FERREDB"."TBL_BODEGAS" ("ID_BODEGA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_INVENTARIO_ARTICULOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_INVENTARIO_ARTICULOS" ON "FERREDB"."TBL_INVENTARIO_ARTICULOS" ("ID_ARTICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_INGRESOS_DEV
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_INGRESOS_DEV" ON "FERREDB"."TBL_INGRESOS_DEV" ("ID_INGRESO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_TIPO_CIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_TIPO_CIA" ON "FERREDB"."TBL_TIPO_CIA" ("ID_TIPO_CIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_PROVINCIAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_PROVINCIAS" ON "FERREDB"."TBL_PROVINCIAS" ("ID_PROVINCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_DETALLE_VENTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_DETALLE_VENTA" ON "FERREDB"."TBL_DETALLE_VENTA" ("ID_DETALLE_VENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_TIPO_RELACION
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_TIPO_RELACION" ON "FERREDB"."TBL_TIPO_RELACION" ("ID_TIPO_RELACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_TIPO_IDENTIFICACION
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_TIPO_IDENTIFICACION" ON "FERREDB"."TBL_TIPO_IDENTIFICACION" ("ID_TIPO_IDENTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  Constraints for Table TBL_PERMISOS_USUARIOS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_PERMISOS_USUARIOS" ADD CONSTRAINT "PK_TBL_PERMISOS_USUARIOS" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_PERMISOS_USUARIOS" MODIFY ("ID_ROL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_DETALLE_DEV
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_DETALLE_DEV" ADD CONSTRAINT "PK_TBL_DETALLE_DEV" PRIMARY KEY ("ID_ING_DEV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_DETALLE_DEV" MODIFY ("ID_ING_DEV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_MONEDAS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_MONEDAS" ADD CONSTRAINT "PK_TBL_MONEDAS" PRIMARY KEY ("ID_MONEDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_MONEDAS" MODIFY ("ID_MONEDA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_EMPRESA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_EMPRESA" ADD CONSTRAINT "PK_TBL_EMPRESA" PRIMARY KEY ("ID_CIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_EMPRESA" MODIFY ("ID_CIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_BODEGAS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_BODEGAS" ADD CONSTRAINT "PK_TBL_BODEGAS" PRIMARY KEY ("ID_BODEGA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_BODEGAS" MODIFY ("ID_BODEGA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_VENTAS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_VENTAS" ADD CONSTRAINT "PK_TBL_VENTAS" PRIMARY KEY ("ID_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_VENTAS" MODIFY ("ID_VENTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_IDENTIFICACION
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_TIPO_IDENTIFICACION" ADD CONSTRAINT "PK_TBL_TIPO_IDENTIFICACION" PRIMARY KEY ("ID_TIPO_IDENTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_TIPO_IDENTIFICACION" MODIFY ("ID_TIPO_IDENTIFICACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_INGRESOS_DEV
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_INGRESOS_DEV" ADD CONSTRAINT "PK_TBL_INGRESOS_DEV" PRIMARY KEY ("ID_INGRESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_INGRESOS_DEV" MODIFY ("ID_INGRESO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_DETALLE_VENTA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_DETALLE_VENTA" ADD CONSTRAINT "PK_TBL_DETALLE_VENTA" PRIMARY KEY ("ID_DETALLE_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_DETALLE_VENTA" MODIFY ("ID_DETALLE_VENTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_INVENTARIO_ARTICULOS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_INVENTARIO_ARTICULOS" ADD CONSTRAINT "PK_TBL_INVENTARIO_ARTICULOS" PRIMARY KEY ("ID_ARTICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_INVENTARIO_ARTICULOS" MODIFY ("ID_ARTICULO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_RELACION
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_TIPO_RELACION" MODIFY ("ID_TIPO_RELACION" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_TIPO_RELACION" ADD CONSTRAINT "PK_TBL_TIPO_RELACION" PRIMARY KEY ("ID_TIPO_RELACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CATEGORIA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_CATEGORIA" ADD CONSTRAINT "PK_TBL_CATEGORIA" PRIMARY KEY ("ID_CATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_CATEGORIA" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_UND_MED
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_UND_MED" ADD CONSTRAINT "PK_TBL_UND_MED" PRIMARY KEY ("ID_UND_MEDIDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_UND_MED" MODIFY ("ID_UND_MEDIDA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_CLIENT_PROV
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_CLIENT_PROV" ADD CONSTRAINT "PK_TBL_CLIENT_PROV" PRIMARY KEY ("ID_CLI_PROV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_CLIENT_PROV" MODIFY ("ID_CLI_PROV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_PROVINCIAS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_PROVINCIAS" ADD CONSTRAINT "PK_TBL_PROVINCIAS" PRIMARY KEY ("ID_PROVINCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_PROVINCIAS" MODIFY ("ID_PROVINCIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_CIA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_TIPO_CIA" ADD CONSTRAINT "PK_TBL_TIPO_CIA" PRIMARY KEY ("ID_TIPO_CIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_TIPO_CIA" MODIFY ("ID_TIPO_CIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_USUARIOS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_USUARIOS" ADD CONSTRAINT "PK_TBL_USUARIOS" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_USUARIOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_PERSONERIA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_TIPO_PERSONERIA" MODIFY ("ID_TIPO_PERSONERIA" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_TIPO_PERSONERIA" ADD CONSTRAINT "PK_TBL_TIPO_PERSONERIA" PRIMARY KEY ("ID_TIPO_PERSONERIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_BODEGAS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_BODEGAS" ADD CONSTRAINT "FK_TBL_BODE_REF_EMP_B_TBL_EMPR" FOREIGN KEY ("ID_CIA")
	  REFERENCES "FERREDB"."TBL_EMPRESA" ("ID_CIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_CLIENT_PROV
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_CLIENT_PROV" ADD CONSTRAINT "FK_TBL_CLIE_REF_EMP_C_TBL_EMPR" FOREIGN KEY ("ID_CIA")
	  REFERENCES "FERREDB"."TBL_EMPRESA" ("ID_CIA") ENABLE;
  ALTER TABLE "FERREDB"."TBL_CLIENT_PROV" ADD CONSTRAINT "FK_TBL_CLIE_REF_PROV__TBL_PROV" FOREIGN KEY ("ID_PROVINCIA")
	  REFERENCES "FERREDB"."TBL_PROVINCIAS" ("ID_PROVINCIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_DETALLE_DEV
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_DETALLE_DEV" ADD CONSTRAINT "FK_TBL_DETA_REF_DET_I_TBL_INGR" FOREIGN KEY ("ID_INGRESO")
	  REFERENCES "FERREDB"."TBL_INGRESOS_DEV" ("ID_INGRESO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_DETALLE_VENTA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_DETALLE_VENTA" ADD CONSTRAINT "FK_TBL_DETA_REF_BODEG_TBL_BODE" FOREIGN KEY ("ID_BODEGA")
	  REFERENCES "FERREDB"."TBL_BODEGAS" ("ID_BODEGA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_EMPRESA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_EMPRESA" ADD CONSTRAINT "FK_TBL_EMPR_REF_CIA_E_TBL_TIPO" FOREIGN KEY ("ID_TIPO_CIA")
	  REFERENCES "FERREDB"."TBL_TIPO_CIA" ("ID_TIPO_CIA") ENABLE;
  ALTER TABLE "FERREDB"."TBL_EMPRESA" ADD CONSTRAINT "FK_TBL_EMPR_REF_EMPRE_TBL_PROV" FOREIGN KEY ("ID_PROVINCIA")
	  REFERENCES "FERREDB"."TBL_PROVINCIAS" ("ID_PROVINCIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_INGRESOS_DEV
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_INGRESOS_DEV" ADD CONSTRAINT "FK_TBL_INGR_REF_BOD_D_TBL_BODE" FOREIGN KEY ("ID_BODEGA")
	  REFERENCES "FERREDB"."TBL_BODEGAS" ("ID_BODEGA") ENABLE;
  ALTER TABLE "FERREDB"."TBL_INGRESOS_DEV" ADD CONSTRAINT "FK_TBL_INGR_REF_DEV_V_TBL_VENT" FOREIGN KEY ("ID_VENTA")
	  REFERENCES "FERREDB"."TBL_VENTAS" ("ID_VENTA") ENABLE;
  ALTER TABLE "FERREDB"."TBL_INGRESOS_DEV" ADD CONSTRAINT "FK_TBL_INGR_REV_DEB_E_TBL_EMPR" FOREIGN KEY ("ID_CIA")
	  REFERENCES "FERREDB"."TBL_EMPRESA" ("ID_CIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_INVENTARIO_ARTICULOS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_INVENTARIO_ARTICULOS" ADD CONSTRAINT "FK_TBL_INVE_REF_ART_B_TBL_BODE" FOREIGN KEY ("ID_BODEGA")
	  REFERENCES "FERREDB"."TBL_BODEGAS" ("ID_BODEGA") ENABLE;
  ALTER TABLE "FERREDB"."TBL_INVENTARIO_ARTICULOS" ADD CONSTRAINT "FK_TBL_INVE_REF_ART_U_TBL_UND_" FOREIGN KEY ("ID_UND_MEDIDA")
	  REFERENCES "FERREDB"."TBL_UND_MED" ("ID_UND_MEDIDA") ENABLE;
  ALTER TABLE "FERREDB"."TBL_INVENTARIO_ARTICULOS" ADD CONSTRAINT "FK_TBL_INVE_REF_CATEG_TBL_CATE" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "FERREDB"."TBL_CATEGORIA" ("ID_CATEGORIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_TIPO_CAMBIO
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_TIPO_CAMBIO" ADD CONSTRAINT "FK_TBL_TIPO_REF_TC_MO_TBL_MONE" FOREIGN KEY ("ID_MONEDA")
	  REFERENCES "FERREDB"."TBL_MONEDAS" ("ID_MONEDA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_USUARIOS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_USUARIOS" ADD CONSTRAINT "FK_TBL_USUA_REF_USER__TBL_PERM" FOREIGN KEY ("ID_ROL")
	  REFERENCES "FERREDB"."TBL_PERMISOS_USUARIOS" ("ID_ROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_VENTAS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_VENTAS" ADD CONSTRAINT "FK_TBL_VENT_REF_DET_V_TBL_DETA" FOREIGN KEY ("ID_DETALLE_VENTA")
	  REFERENCES "FERREDB"."TBL_DETALLE_VENTA" ("ID_DETALLE_VENTA") ENABLE;
  ALTER TABLE "FERREDB"."TBL_VENTAS" ADD CONSTRAINT "FK_TBL_VENT_REF_EMPRE_TBL_EMPR" FOREIGN KEY ("ID_CIA")
	  REFERENCES "FERREDB"."TBL_EMPRESA" ("ID_CIA") ENABLE;
  ALTER TABLE "FERREDB"."TBL_VENTAS" ADD CONSTRAINT "FK_TBL_VENT_REF_USER__TBL_USUA" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "FERREDB"."TBL_USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  DDL for Function EXISTE_PROV
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "FERREDB"."EXISTE_PROV" (PROV IN TBL_PROVINCIAS.PROVINCIA%TYPE)
RETURN BOOLEAN IS

FLAG NUMBER;
BANDERA BOOLEAN := TRUE;
BEGIN
    SELECT COUNT (*)
    INTO FLAG
    FROM TBL_PROVINCIAS
    WHERE PROVINCIA = PROV;
    IF FLAG > 0 THEN
      BANDERA :=  TRUE;
    ELSE
      BANDERA := FALSE;
    END IF;
    RETURN BANDERA;
END;

/
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_TBL_PROVINCIAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."ACTUALIZAR_TBL_PROVINCIAS" 
(IDPROV IN NUMBER, PROV IN VARCHAR2)
AS
  VARID NUMBER:= IDPROV;
  VARPROV VARCHAR2(20):= PROV;
BEGIN
      UPDATE TBL_PROVINCIAS
      SET PROVINCIA = VARPROV
      WHERE ID_PROVINCIA = VARID;
END ACTUALIZAR_TBL_PROVINCIAS;

/
--------------------------------------------------------
--  DDL for Procedure BORRAR_TBL_PROVINCIAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."BORRAR_TBL_PROVINCIAS" 
(ID_PROV IN NUMBER)
AS 
  VARID number:=ID_PROV;
BEGIN
    DELETE FROM TBL_PROVINCIAS
    WHERE ID_PROVINCIA = VARID;
END BORRAR_TBL_PROVINCIAS;

/
--------------------------------------------------------
--  DDL for Procedure BUSCAR_TBL_PROVINCIAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."BUSCAR_TBL_PROVINCIAS" 
(PROV IN TBL_PROVINCIAS.PROVINCIA%TYPE, 
REGISTROS OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN REGISTROS FOR SELECT ID_PROVINCIA,PROVINCIA 
    FROM TBL_PROVINCIAS
    WHERE PROVINCIA LIKE '%' ||PROV|| '%'
    ORDER BY ID_PROVINCIA;
END BUSCAR_TBL_PROVINCIAS;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_TBL_PROVINCIAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."INSERTAR_TBL_PROVINCIAS" (ID IN NUMBER, NOMB_PROV IN VARCHAR2 )
AS 
BEGIN
    INSERT INTO TBL_PROVINCIAS(ID_PROVINCIA,PROVINCIA)
    VALUES (ID, NOMB_PROV);
    COMMIT;
END INSERTAR_TBL_PROVINCIAS;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_TBL_TIPO_CIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."INSERTAR_TBL_TIPO_CIA" 
(IDEMP IN NUMBER,
TIPO_EMP IN VARCHAR2,
DESCRIP IN VARCHAR2)
AS 
BEGIN
    INSERT INTO TBL_TIPO_CIA(ID_TIPO_CIA,TIPO_EMPRESA,DESCRIPCION)
    VALUES (IDEMP, TIPO_EMP,DESCRIP);
    COMMIT;
END INSERTAR_TBL_TIPO_CIA;

/
--------------------------------------------------------
--  DDL for Procedure LISTAR_TBL_PROVINCIAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."LISTAR_TBL_PROVINCIAS" (REGISTROS OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN REGISTROS FOR SELECT * FROM LISTAR_PROVINCIAS;
END LISTAR_TBL_PROVINCIAS;

/*SET AUTOPRINT ON;

VARIABLE MEMORIA SYS_REFCURSOR;
EXECUTE LISTARPROV(:MEMORIA);*/

/
--------------------------------------------------------
--  DDL for Procedure LISTAR_TIPO_CIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."LISTAR_TIPO_CIA" (REGISTROS OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN REGISTROS FOR SELECT * FROM LISTAR_TBL_TIPO_CIA;
END LISTAR_TIPO_CIA;

/
