--------------------------------------------------------
-- Archivo creado  - lunes-junio-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEC_ID_PROV_TBL_PROVINCIAS
--------------------------------------------------------

   CREATE SEQUENCE  "FERREDB"."SEC_ID_PROV_TBL_PROVINCIAS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table TBL_BODEGAS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_BODEGAS" 
   (	"ID_CIA" NUMBER(*,0), 
	"ID_BODEGA" NUMBER(*,0), 
	"ID_ARTICULO" NUMBER(*,0), 
	"COD_BODEGA" VARCHAR2(10 BYTE), 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"UBICACION" VARCHAR2(100 BYTE), 
	"STOCK" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_CATEGORIA
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_CATEGORIA" 
   (	"ID_CATEGORIA" NUMBER(*,0), 
	"CATEGORIA" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_CLIENT_PROV
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_CLIENT_PROV" 
   (	"ID_CIA" NUMBER(*,0), 
	"ID_CLI_PROV" NUMBER(*,0), 
	"ID_TIPO_IDENTIFICACION" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"NUM_DOC" VARCHAR2(20 BYTE), 
	"ID_PROVINCIA" NUMBER(*,0), 
	"DIRECCION" VARCHAR2(200 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"WEB" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_DETALLE_DEV
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_DETALLE_DEV" 
   (	"ID_ING_DEV" NUMBER(*,0), 
	"ID_INGRESO" NUMBER(*,0), 
	"ID_ARTICULO" NUMBER(*,0), 
	"CANTIDAD" NUMBER(*,0), 
	"PRECIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_DETALLE_VENTA
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_DETALLE_VENTA" 
   (	"ID_DETALLE_VENTA" NUMBER(*,0), 
	"ID_VENTA" NUMBER(*,0), 
	"ID_ARTICULO" NUMBER(*,0), 
	"ID_BODEGA" NUMBER(*,0), 
	"PRECIO" NUMBER(11,2), 
	"DESCUENTO" NUMBER(11,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_EMPRESA
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_EMPRESA" 
   (	"ID_CIA" NUMBER(*,0), 
	"ID_TIPO_CIA" NUMBER(*,0), 
	"ID_TIPO_IDENTIFICACION" NUMBER(*,0), 
	"NUM_ID" VARCHAR2(20 BYTE), 
	"RAZON_SOCIAL" VARCHAR2(50 BYTE), 
	"NOMBRE" CHAR(10 BYTE), 
	"DIRECCION" VARCHAR2(255 BYTE), 
	"TEL1" VARCHAR2(15 BYTE), 
	"TEL2" VARCHAR2(15 BYTE), 
	"FAX" VARCHAR2(15 BYTE), 
	"CP" VARCHAR2(10 BYTE), 
	"WEB" VARCHAR2(60 BYTE), 
	"E_MAIL" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_INGRESOS_DEV
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_INGRESOS_DEV" 
   (	"ID_INGRESO" NUMBER(*,0), 
	"ID_CIA" NUMBER(*,0), 
	"ID_CLI_PROV" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"TIPO_COMPROBANTE" VARCHAR2(20 BYTE), 
	"CONSECUTIVO" NUMBER(*,0), 
	"FECHA" DATE, 
	"IMPUESTO" NUMBER(11,2), 
	"TOTAL" NUMBER(11,2), 
	"ESTADO" VARCHAR2(20 BYTE), 
	"ID_BODEGA" NUMBER(*,0), 
	"ID_VENTA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_INVENTARIO_ARTICULOS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_INVENTARIO_ARTICULOS" 
   (	"ID_ARTICULO" NUMBER(*,0), 
	"ID_CATEGORIA" NUMBER(*,0), 
	"ID_BODEGA" NUMBER(*,0), 
	"CODIGO" VARCHAR2(50 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"ID_UND_MEDIDA" NUMBER(*,0), 
	"PRECIO_VENTA" NUMBER(11,2), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"IMAGEN" VARCHAR2(20 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_MONEDAS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_MONEDAS" 
   (	"ID_MONEDA" NUMBER(*,0), 
	"COD_MONEDA" VARCHAR2(10 BYTE), 
	"DESCRIPCION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_PERMISOS_USUARIOS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_PERMISOS_USUARIOS" 
   (	"ID_ROL" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_PROVINCIAS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_PROVINCIAS" 
   (	"ID_PROVINCIA" NUMBER(*,0), 
	"PROVINCIA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_CAMBIO
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_TIPO_CAMBIO" 
   (	"ID_TC" NUMBER(*,0), 
	"ID_MONEDA" NUMBER(*,0), 
	"COMPRA" NUMBER(*,0), 
	"VENTA" NUMBER(*,0), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_CIA
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_TIPO_CIA" 
   (	"ID_TIPO_CIA" NUMBER(*,0), 
	"TIPO_EMPRESA" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_IDENTIFICACION
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_TIPO_IDENTIFICACION" 
   (	"ID_TIPO_IDENTIFICACION" NUMBER(*,0), 
	"PERSONERIA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_PERSONERIA
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_TIPO_PERSONERIA" 
   (	"ID_TIPO_PERSONERIA" NUMBER(*,0), 
	"PERSONERIA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_TIPO_RELACION
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_TIPO_RELACION" 
   (	"ID_TIPO_RELACION" NUMBER(*,0), 
	"RELACION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_UND_MED
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_UND_MED" 
   (	"ID_UND_MEDIDA" NUMBER(*,0), 
	"COD_MEDIDA" VARCHAR2(10 BYTE), 
	"DESCRIPCION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_USUARIOS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_USUARIOS" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"ID_ROL" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDO_1" VARCHAR2(50 BYTE), 
	"APELLIDO_2" VARCHAR2(50 BYTE), 
	"ID_TIPO_DOCUMENTO" VARCHAR2(20 BYTE), 
	"NUM_IDENTIFICACION" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(255 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(15 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Table TBL_VENTAS
--------------------------------------------------------

  CREATE TABLE "FERREDB"."TBL_VENTAS" 
   (	"ID_CIA" NUMBER(*,0), 
	"ID_VENTA" NUMBER(*,0), 
	"ID_DETALLE_VENTA" NUMBER(*,0), 
	"ID_CLIENTE" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"ID_COMPROBANTE" VARCHAR2(10 BYTE), 
	"FECHA" DATE, 
	"HORA" DATE, 
	"IMPUESTO" NUMBER(10,2), 
	"TOTAL" NUMBER(10,2), 
	"ESTADO" CHAR(1 BYTE), 
	"ID_TC" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;

   COMMENT ON TABLE "FERREDB"."TBL_VENTAS"  IS 'Esta Tabla lleva control de las transacciones de ventas o salidas de la bodega';
--------------------------------------------------------
--  DDL for View LISTAR_PROVINCIAS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "FERREDB"."LISTAR_PROVINCIAS" ("ID_PROVINCIA", "PROVINCIA") AS 
  SELECT "ID_PROVINCIA","PROVINCIA"
FROM TBL_PROVINCIAS
ORDER BY ID_PROVINCIA;
REM INSERTING into FERREDB.TBL_BODEGAS
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_CATEGORIA
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_CLIENT_PROV
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_DETALLE_DEV
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_DETALLE_VENTA
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_EMPRESA
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_INGRESOS_DEV
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_INVENTARIO_ARTICULOS
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_MONEDAS
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_PERMISOS_USUARIOS
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_PROVINCIAS
SET DEFINE OFF;
Insert into FERREDB.TBL_PROVINCIAS (ID_PROVINCIA,PROVINCIA) values ('2','ALAJUELA');
Insert into FERREDB.TBL_PROVINCIAS (ID_PROVINCIA,PROVINCIA) values ('3','CARTAGO');
Insert into FERREDB.TBL_PROVINCIAS (ID_PROVINCIA,PROVINCIA) values ('4','HEREDIA');
Insert into FERREDB.TBL_PROVINCIAS (ID_PROVINCIA,PROVINCIA) values ('6','PUNTARENAS');
Insert into FERREDB.TBL_PROVINCIAS (ID_PROVINCIA,PROVINCIA) values ('7','HEREDIA');
Insert into FERREDB.TBL_PROVINCIAS (ID_PROVINCIA,PROVINCIA) values ('5','GUANACASTE');
Insert into FERREDB.TBL_PROVINCIAS (ID_PROVINCIA,PROVINCIA) values ('1','SAN JOSE');
REM INSERTING into FERREDB.TBL_TIPO_CAMBIO
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_TIPO_CIA
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_TIPO_IDENTIFICACION
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_TIPO_PERSONERIA
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_TIPO_RELACION
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_UND_MED
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_USUARIOS
SET DEFINE OFF;
REM INSERTING into FERREDB.TBL_VENTAS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_TBL_EMPRESA
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_EMPRESA" ON "FERREDB"."TBL_EMPRESA" ("ID_CIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_PERMISOS_USUARIOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_PERMISOS_USUARIOS" ON "FERREDB"."TBL_PERMISOS_USUARIOS" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_VENTAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_VENTAS" ON "FERREDB"."TBL_VENTAS" ("ID_VENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_CATEGORIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_CATEGORIA" ON "FERREDB"."TBL_CATEGORIA" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_TIPO_PERSONERIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_TIPO_PERSONERIA" ON "FERREDB"."TBL_TIPO_PERSONERIA" ("ID_TIPO_PERSONERIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_DETALLE_DEV
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_DETALLE_DEV" ON "FERREDB"."TBL_DETALLE_DEV" ("ID_ING_DEV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_UND_MED
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_UND_MED" ON "FERREDB"."TBL_UND_MED" ("ID_UND_MEDIDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_CLIENT_PROV
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_CLIENT_PROV" ON "FERREDB"."TBL_CLIENT_PROV" ("ID_CLI_PROV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_USUARIOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_USUARIOS" ON "FERREDB"."TBL_USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_MONEDAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_MONEDAS" ON "FERREDB"."TBL_MONEDAS" ("ID_MONEDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_BODEGAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_BODEGAS" ON "FERREDB"."TBL_BODEGAS" ("ID_BODEGA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_INVENTARIO_ARTICULOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_INVENTARIO_ARTICULOS" ON "FERREDB"."TBL_INVENTARIO_ARTICULOS" ("ID_ARTICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_INGRESOS_DEV
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_INGRESOS_DEV" ON "FERREDB"."TBL_INGRESOS_DEV" ("ID_INGRESO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_TIPO_CIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_TIPO_CIA" ON "FERREDB"."TBL_TIPO_CIA" ("ID_TIPO_CIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_PROVINCIAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_PROVINCIAS" ON "FERREDB"."TBL_PROVINCIAS" ("ID_PROVINCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_DETALLE_VENTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_DETALLE_VENTA" ON "FERREDB"."TBL_DETALLE_VENTA" ("ID_DETALLE_VENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_TIPO_RELACION
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_TIPO_RELACION" ON "FERREDB"."TBL_TIPO_RELACION" ("ID_TIPO_RELACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  DDL for Index PK_TBL_TIPO_IDENTIFICACION
--------------------------------------------------------

  CREATE UNIQUE INDEX "FERREDB"."PK_TBL_TIPO_IDENTIFICACION" ON "FERREDB"."TBL_TIPO_IDENTIFICACION" ("ID_TIPO_IDENTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ" ;
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_IDENTIFICACION
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_TIPO_IDENTIFICACION" MODIFY ("ID_TIPO_IDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_TIPO_IDENTIFICACION" ADD CONSTRAINT "PK_TBL_TIPO_IDENTIFICACION" PRIMARY KEY ("ID_TIPO_IDENTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_CIA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_TIPO_CIA" MODIFY ("ID_TIPO_CIA" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_TIPO_CIA" ADD CONSTRAINT "PK_TBL_TIPO_CIA" PRIMARY KEY ("ID_TIPO_CIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CATEGORIA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_CATEGORIA" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_CATEGORIA" ADD CONSTRAINT "PK_TBL_CATEGORIA" PRIMARY KEY ("ID_CATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_DETALLE_VENTA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_DETALLE_VENTA" MODIFY ("ID_DETALLE_VENTA" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_DETALLE_VENTA" ADD CONSTRAINT "PK_TBL_DETALLE_VENTA" PRIMARY KEY ("ID_DETALLE_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_EMPRESA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_EMPRESA" MODIFY ("ID_CIA" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_EMPRESA" ADD CONSTRAINT "PK_TBL_EMPRESA" PRIMARY KEY ("ID_CIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_INVENTARIO_ARTICULOS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_INVENTARIO_ARTICULOS" MODIFY ("ID_ARTICULO" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_INVENTARIO_ARTICULOS" ADD CONSTRAINT "PK_TBL_INVENTARIO_ARTICULOS" PRIMARY KEY ("ID_ARTICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_DETALLE_DEV
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_DETALLE_DEV" MODIFY ("ID_ING_DEV" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_DETALLE_DEV" ADD CONSTRAINT "PK_TBL_DETALLE_DEV" PRIMARY KEY ("ID_ING_DEV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_PERMISOS_USUARIOS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_PERMISOS_USUARIOS" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_PERMISOS_USUARIOS" ADD CONSTRAINT "PK_TBL_PERMISOS_USUARIOS" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_BODEGAS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_BODEGAS" MODIFY ("ID_BODEGA" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_BODEGAS" ADD CONSTRAINT "PK_TBL_BODEGAS" PRIMARY KEY ("ID_BODEGA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_INGRESOS_DEV
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_INGRESOS_DEV" MODIFY ("ID_INGRESO" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_INGRESOS_DEV" ADD CONSTRAINT "PK_TBL_INGRESOS_DEV" PRIMARY KEY ("ID_INGRESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_PROVINCIAS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_PROVINCIAS" MODIFY ("ID_PROVINCIA" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_PROVINCIAS" ADD CONSTRAINT "PK_TBL_PROVINCIAS" PRIMARY KEY ("ID_PROVINCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_USUARIOS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_USUARIOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_USUARIOS" ADD CONSTRAINT "PK_TBL_USUARIOS" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_RELACION
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_TIPO_RELACION" ADD CONSTRAINT "PK_TBL_TIPO_RELACION" PRIMARY KEY ("ID_TIPO_RELACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_TIPO_RELACION" MODIFY ("ID_TIPO_RELACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_VENTAS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_VENTAS" MODIFY ("ID_VENTA" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_VENTAS" ADD CONSTRAINT "PK_TBL_VENTAS" PRIMARY KEY ("ID_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CLIENT_PROV
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_CLIENT_PROV" MODIFY ("ID_CLI_PROV" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_CLIENT_PROV" ADD CONSTRAINT "PK_TBL_CLIENT_PROV" PRIMARY KEY ("ID_CLI_PROV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_MONEDAS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_MONEDAS" MODIFY ("ID_MONEDA" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_MONEDAS" ADD CONSTRAINT "PK_TBL_MONEDAS" PRIMARY KEY ("ID_MONEDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_PERSONERIA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_TIPO_PERSONERIA" ADD CONSTRAINT "PK_TBL_TIPO_PERSONERIA" PRIMARY KEY ("ID_TIPO_PERSONERIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
  ALTER TABLE "FERREDB"."TBL_TIPO_PERSONERIA" MODIFY ("ID_TIPO_PERSONERIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_UND_MED
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_UND_MED" MODIFY ("ID_UND_MEDIDA" NOT NULL ENABLE);
  ALTER TABLE "FERREDB"."TBL_UND_MED" ADD CONSTRAINT "PK_TBL_UND_MED" PRIMARY KEY ("ID_UND_MEDIDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_OBJ"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_BODEGAS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_BODEGAS" ADD CONSTRAINT "FK_TBL_BODE_REF_EMP_B_TBL_EMPR" FOREIGN KEY ("ID_CIA")
	  REFERENCES "FERREDB"."TBL_EMPRESA" ("ID_CIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_CLIENT_PROV
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_CLIENT_PROV" ADD CONSTRAINT "FK_TBL_CLIE_REF_EMP_C_TBL_EMPR" FOREIGN KEY ("ID_CIA")
	  REFERENCES "FERREDB"."TBL_EMPRESA" ("ID_CIA") ENABLE;
  ALTER TABLE "FERREDB"."TBL_CLIENT_PROV" ADD CONSTRAINT "FK_TBL_CLIE_REF_PROV__TBL_PROV" FOREIGN KEY ("ID_PROVINCIA")
	  REFERENCES "FERREDB"."TBL_PROVINCIAS" ("ID_PROVINCIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_DETALLE_DEV
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_DETALLE_DEV" ADD CONSTRAINT "FK_TBL_DETA_REF_DET_I_TBL_INGR" FOREIGN KEY ("ID_INGRESO")
	  REFERENCES "FERREDB"."TBL_INGRESOS_DEV" ("ID_INGRESO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_DETALLE_VENTA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_DETALLE_VENTA" ADD CONSTRAINT "FK_TBL_DETA_REF_BODEG_TBL_BODE" FOREIGN KEY ("ID_BODEGA")
	  REFERENCES "FERREDB"."TBL_BODEGAS" ("ID_BODEGA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_EMPRESA
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_EMPRESA" ADD CONSTRAINT "FK_TBL_EMPR_REF_CIA_E_TBL_TIPO" FOREIGN KEY ("ID_TIPO_CIA")
	  REFERENCES "FERREDB"."TBL_TIPO_CIA" ("ID_TIPO_CIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_INGRESOS_DEV
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_INGRESOS_DEV" ADD CONSTRAINT "FK_TBL_INGR_REF_BOD_D_TBL_BODE" FOREIGN KEY ("ID_BODEGA")
	  REFERENCES "FERREDB"."TBL_BODEGAS" ("ID_BODEGA") ENABLE;
  ALTER TABLE "FERREDB"."TBL_INGRESOS_DEV" ADD CONSTRAINT "FK_TBL_INGR_REF_DEV_V_TBL_VENT" FOREIGN KEY ("ID_VENTA")
	  REFERENCES "FERREDB"."TBL_VENTAS" ("ID_VENTA") ENABLE;
  ALTER TABLE "FERREDB"."TBL_INGRESOS_DEV" ADD CONSTRAINT "FK_TBL_INGR_REV_DEB_E_TBL_EMPR" FOREIGN KEY ("ID_CIA")
	  REFERENCES "FERREDB"."TBL_EMPRESA" ("ID_CIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_INVENTARIO_ARTICULOS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_INVENTARIO_ARTICULOS" ADD CONSTRAINT "FK_TBL_INVE_REF_ART_B_TBL_BODE" FOREIGN KEY ("ID_BODEGA")
	  REFERENCES "FERREDB"."TBL_BODEGAS" ("ID_BODEGA") ENABLE;
  ALTER TABLE "FERREDB"."TBL_INVENTARIO_ARTICULOS" ADD CONSTRAINT "FK_TBL_INVE_REF_ART_U_TBL_UND_" FOREIGN KEY ("ID_UND_MEDIDA")
	  REFERENCES "FERREDB"."TBL_UND_MED" ("ID_UND_MEDIDA") ENABLE;
  ALTER TABLE "FERREDB"."TBL_INVENTARIO_ARTICULOS" ADD CONSTRAINT "FK_TBL_INVE_REF_CATEG_TBL_CATE" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "FERREDB"."TBL_CATEGORIA" ("ID_CATEGORIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_TIPO_CAMBIO
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_TIPO_CAMBIO" ADD CONSTRAINT "FK_TBL_TIPO_REF_TC_MO_TBL_MONE" FOREIGN KEY ("ID_MONEDA")
	  REFERENCES "FERREDB"."TBL_MONEDAS" ("ID_MONEDA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_USUARIOS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_USUARIOS" ADD CONSTRAINT "FK_TBL_USUA_REF_USER__TBL_PERM" FOREIGN KEY ("ID_ROL")
	  REFERENCES "FERREDB"."TBL_PERMISOS_USUARIOS" ("ID_ROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_VENTAS
--------------------------------------------------------

  ALTER TABLE "FERREDB"."TBL_VENTAS" ADD CONSTRAINT "FK_TBL_VENT_REF_DET_V_TBL_DETA" FOREIGN KEY ("ID_DETALLE_VENTA")
	  REFERENCES "FERREDB"."TBL_DETALLE_VENTA" ("ID_DETALLE_VENTA") ENABLE;
  ALTER TABLE "FERREDB"."TBL_VENTAS" ADD CONSTRAINT "FK_TBL_VENT_REF_EMPRE_TBL_EMPR" FOREIGN KEY ("ID_CIA")
	  REFERENCES "FERREDB"."TBL_EMPRESA" ("ID_CIA") ENABLE;
  ALTER TABLE "FERREDB"."TBL_VENTAS" ADD CONSTRAINT "FK_TBL_VENT_REF_USER__TBL_USUA" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "FERREDB"."TBL_USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_TBL_PROVINCIAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."ACTUALIZAR_TBL_PROVINCIAS" 
(IDPROV IN NUMBER, PROV IN VARCHAR2)
AS
  VARID NUMBER:= IDPROV;
  VARPROV VARCHAR2(20):= PROV;
BEGIN
      UPDATE TBL_PROVINCIAS
      SET PROVINCIA = VARPROV
      WHERE ID_PROVINCIA = VARID;
END ACTUALIZAR_TBL_PROVINCIAS;

/
--------------------------------------------------------
--  DDL for Procedure BORRAR_TBL_PROVINCIAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."BORRAR_TBL_PROVINCIAS" 
(ID_PROV IN NUMBER)
AS 
  VARID number:=ID_PROV;
BEGIN
    DELETE FROM TBL_PROVINCIAS
    WHERE ID_PROVINCIA = VARID;
END BORRAR_TBL_PROVINCIAS;

/
--------------------------------------------------------
--  DDL for Procedure BUSCAR_TBL_PROVINCIAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."BUSCAR_TBL_PROVINCIAS" 
(PROV IN TBL_PROVINCIAS.PROVINCIA%TYPE, 
REGISTROS OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN REGISTROS FOR SELECT ID_PROVINCIA,PROVINCIA 
    FROM TBL_PROVINCIAS
    WHERE PROVINCIA LIKE '%' ||PROV|| '%'
    ORDER BY ID_PROVINCIA;
END BUSCAR_TBL_PROVINCIAS;

/
--------------------------------------------------------
--  DDL for Procedure CONSULTA_ULT_ID_TBL_PROV
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."CONSULTA_ULT_ID_TBL_PROV" (REGISTROS OUT SYS_REFCURSOR)
AS 
BEGIN
  OPEN REGISTROS FOR SELECT *
  FROM 
  (SELECT ID_PROVINCIA FROM TBL_PROVINCIAS 
  ORDER BY TBL_PROVINCIAS.ID_PROVINCIA DESC)
  WHERE ROWNUM = 1;
END CONSULTA_ULT_ID_TBL_PROV;

/
--------------------------------------------------------
--  DDL for Procedure EXISTE_TBL_PROVINCIAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."EXISTE_TBL_PROVINCIAS" 
(PROV IN TBL_PROVINCIAS.PROVINCIA%TYPE,
REGISTROS OUT SYS_REFCURSOR)
IS
FLAG NUMBER;
BEGIN
      OPEN REGISTROS FOR SELECT COUNT (*)
      INTO FLAG
      FROM TBL_PROVINCIAS
      WHERE PROVINCIA = PROV;
END;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_TBL_PROVINCIAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."INSERTAR_TBL_PROVINCIAS" (ID IN NUMBER, NOMB_PROV IN VARCHAR2 )
AS 
BEGIN
    INSERT INTO TBL_PROVINCIAS(ID_PROVINCIA,PROVINCIA)
    VALUES (ID, NOMB_PROV);
    COMMIT;
END INSERTAR_TBL_PROVINCIAS;

/
--------------------------------------------------------
--  DDL for Procedure LISTAR_TBL_PROVINCIAS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "FERREDB"."LISTAR_TBL_PROVINCIAS" (REGISTROS OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN REGISTROS FOR SELECT * FROM LISTAR_PROVINCIAS;
END LISTAR_TBL_PROVINCIAS;

/*SET AUTOPRINT ON;

VARIABLE MEMORIA SYS_REFCURSOR;
EXECUTE LISTARPROV(:MEMORIA);*/

/
