INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (1,'Sp','Servicios Profesionales');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (2,'m','Metro');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (3,'kg','Kilogramo');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (4,'s','Segundo');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (5,'A','Ampere');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (6,'K','Kelvin');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (7,'mol','Mol');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (8,'cd','Candela');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (9,'m²','metro cuadrado');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (10,'m³','metro cúbico');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (11,'m/s','metro por segundo');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (12,'m/s²','metro por segundo cuadrado');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (13,'1/m','1 por metro');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (14,'kg/m³','kilogramo por metro cúbico');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (15,'A/m²','ampere por metro cuadrado');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (16,'A/m','ampere por metro');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (17,'mol/m³','mol por metro cúbico');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (18,'cd/m²','candela por metro cuadrado');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (19,'1','uno (indice de refracción)');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (20,'rad','radián');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (21,'sr','estereorradián');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (22,'Hz','hertz');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (23,'N','newton');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (24,'Pa','pascal');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (25,'J','Joule');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (26,'W','Watt');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (27,'C','coulomb');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (28,'V','volt');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (29,'F','farad');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (30,'?','ohm');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (31,'S','siemens');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (32,'Wb','weber');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (33,'T','tesla');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (34,'H','henry');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (35,'°C','grado Celsius');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (36,'lm','lumen');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (37,'lx','lux');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (38,'Bq','Becquerel');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (39,'Gy','gray');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (40,'Sv','sievert');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (41,'kat','katal');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (42,'Pa·s','pascal segundo');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (43,'N·m','newton metro');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (44,'N/m','newton por metro');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (45,'rad/s','radián por segundo');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (46,'rad/s²','radián por segundo cuadrado');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (47,'W/m²','watt por metro cuadrado');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (48,'J/K','joule por kelvin');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (49,'J/(kg·K)','joule por kilogramo kelvin');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (50,'J/kg','joule por kilogramo');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (51,'W/(m·K)','watt por metro kevin');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (52,'J/m³','joule por metro cúbico');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (53,'V/m','volt por metro');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (54,'C/m³','coulomb por metro cúbico');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (55,'C/m²','coulomb por metro cuadrado');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (56,'F/m','farad por metro');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (57,'H/m','henry por metro');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (58,'J/mol','joule por mol');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (59,'J/(mol·K)','joule por mol kelvin');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (60,'C/kg','coulomb por kilogramo');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (61,'Gy/s','gray por segundo');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (62,'W/sr','watt por estereorradián');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (63,'W/(m²·sr)','watt por metro cuadrado estereorradián');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (64,'kat/m³','katal por metro cúbico');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (65,'min','minuto');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (66,'h','hora');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (67,'d','día');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (68,'º','grado');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (69,'´','minuto');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (70,'´´','segundo');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (71,'L','litro');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (72,'t','tonelada');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (73,'Np','neper');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (74,'B','bel');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (75,'eV','electronvolt');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (76,'u','unidad de masa atómica unificada');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (77,'ua','unidad astronómica');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (78,'Unid','Unidad');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (79,'Gal','Galón');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (80,'g','Gramo');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (81,'Km','Kilometro');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (82,'ln','pulgada');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (83,'cm','centimetro');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (84,'mL','mililitro');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (85,'mm','Milimetro');
INSERT INTO TBL_UND_MED(ID_und_Medida,Cod_Medida,Descripcion) VALUES (86,'Oz','Onzas');
