CREATE OR REPLACE PROCEDURE "ACTUALIZAR_TBL_EMPRESA" 
(VAR1 IN NUMBER, VAR2 IN NUMBER, VAR3 IN NUMBER,
VAR4 IN VARCHAR2,VAR5 IN VARCHAR2,VAR6 IN VARCHAR2,
VAR7 IN NUMBER,
VAR8 IN VARCHAR2,VAR9 IN VARCHAR2,VAR10 IN VARCHAR2,VAR11 IN VARCHAR2,VAR12 IN VARCHAR2,VAR13 IN VARCHAR2,VAR14 IN VARCHAR2)
AS 
BEGIN
   UPDATE TBL_EMPRESA
   SET ID_CIA = VAR1, ID_TIPO_CIA = VAR2, ID_TIPO_IDENTIFICACION = VAR3, RAZON_SOCIAL=VAR5, NOMBRE=VAR6, ID_PROVINCIA=VAR7, DIRECCION=VAR8, TEL1=VAR9,TEL2=VAR10,FAX=VAR11,CP=VAR12,WEB=VAR13,E_MAIL=VAR14
   WHERE NUM_ID = VAR4;
   COMMIT;
END;

/---------------------------------------------------

CREATE OR REPLACE PROCEDURE "INSERTAR_TBL_EMPRESA" 
(VAR1 IN NUMBER, VAR2 IN NUMBER, VAR3 IN NUMBER,
VAR4 IN VARCHAR2,VAR5 IN VARCHAR2,VAR6 IN VARCHAR2,
VAR7 IN NUMBER,
VAR8 IN VARCHAR2,VAR9 IN VARCHAR2,VAR10 IN VARCHAR2,VAR11 IN VARCHAR2,VAR12 IN VARCHAR2,VAR13 IN VARCHAR2,VAR14 IN VARCHAR2)
AS 
BEGIN
    INSERT INTO TBL_EMPRESA (ID_CIA, ID_TIPO_CIA, ID_TIPO_IDENTIFICACION, NUM_ID, RAZON_SOCIAL, NOMBRE, ID_PROVINCIA, DIRECCION, TEL1,TEL2,FAX,CP,WEB,E_MAIL)
    VALUES (VAR1,VAR2,VAR3,VAR4,VAR5,VAR6,VAR7,VAR8,VAR9,VAR10,VAR11,VAR12,VAR13,VAR14);
    COMMIT;
END INSERTAR_TBL_EMPRESA;

CREATE OR REPLACE PROCEDURE "ACTIV_EMPRESA" 
(VAR15 IN VARCHAR2)
AS
VARID number:=VAR15;
BEGIN
  UPDATE TBL_EMPRESA 
  SET ESTADO = 'ACTIVO'
  WHERE NUM_ID = VARID;
  COMMIT;
END;

CREATE OR REPLACE PROCEDURE "DESACTIV_EMPRESA" 
(VAR15 IN VARCHAR2)
AS
VARID number:=VAR15;
BEGIN
  UPDATE TBL_EMPRESA 
  SET ESTADO = 'INACTIVO'
  WHERE NUM_ID = VARID;
  COMMIT;
END;

CREATE OR REPLACE PROCEDURE "BORRAR_TBL_EMPRESA" 
(VAR15 IN NUMBER)
AS 
  VARID number:=VAR15;
BEGIN
    DELETE FROM TBL_EMPRESA
    WHERE NUM_ID = VARID;
    COMMIT;
END BORRAR_TBL_EMPRESA;

/-------------------------------------
CREATE OR REPLACE PROCEDURE           "BUSCAR_TBL_EMPRESA" 
(NUMID IN TBL_EMPRESA.NUM_ID%TYPE, 
REGISTROS OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN REGISTROS FOR SELECT *
    FROM LISTAR_EMPRESABSC
    WHERE "CÓDIGO" LIKE '%' ||NUMID|| '%'
    ORDER BY "CÓDIGO";
END BUSCAR_TBL_EMPRESA;

/************************************/
CREATE OR REPLACE FORCE VIEW "FERREDB"."LISTAR_EMPRESABSC" ("CÓDIGO", "PERSONERIA", "Nº IDENTIFICACION", "RAZÓN SOCIAL", "TIPO DE COMPAÑIA", "ESTADO") AS 
  SELECT TBL_EMPRESA.ID_CIA, TBL_TIPO_IDENTIFICACION.PERSONERIA, TBL_EMPRESA.NUM_ID, TBL_EMPRESA.RAZON_SOCIAL, TBL_TIPO_CIA.TIPO_EMPRESA, TBL_EMPRESA.ESTADO
FROM TBL_EMPRESA, TBL_TIPO_IDENTIFICACION,TBL_TIPO_CIA
WHERE TBL_TIPO_IDENTIFICACION.ID_TIPO_IDENTIFICACION = TBL_EMPRESA.ID_TIPO_IDENTIFICACION AND  TBL_TIPO_CIA.ID_TIPO_CIA = TBL_EMPRESA.ID_TIPO_CIA
ORDER BY TBL_EMPRESA.ID_CIA;

/**/

CREATE OR REPLACE FORCE VIEW "FERREDB"."LISTAR_EMPREDETALLAD" ("CÓDIGO", "TIPO EMPRESA" ,"PERSONERIA", "Nº IDENTIFICACION", "RAZÓN SOCIAL","NOMBRE","PROVINCIA","DIRECCION","TELÉFONO 1","TELÉFONO 2","FAX","CP","WEB","EMAIL" , "ESTADO") AS 
SELECT TBL_EMPRESA.ID_CIA,TBL_EMPRESA.ID_TIPO_CIA, TBL_TIPO_IDENTIFICACION.PERSONERIA, TBL_EMPRESA.NUM_ID, TBL_EMPRESA.RAZON_SOCIAL,TBL_EMPRESA.NOMBRE,TBL_EMPRESA.ID_PROVINCIA,TBL_EMPRESA.DIRECCION, TBL_EMPRESA.TEL1, TBL_EMPRESA.TEL2, TBL_EMPRESA.FAX, TBL_EMPRESA.CP, TBL_EMPRESA.WEB, TBL_EMPRESA.E_MAIL, TBL_EMPRESA.ESTADO
FROM TBL_EMPRESA, TBL_TIPO_IDENTIFICACION,TBL_TIPO_CIA, TBL_PROVINCIAS
WHERE TBL_TIPO_IDENTIFICACION.ID_TIPO_IDENTIFICACION = TBL_EMPRESA.ID_TIPO_IDENTIFICACION AND  TBL_TIPO_CIA.ID_TIPO_CIA = TBL_EMPRESA.ID_TIPO_CIA AND TBL_PROVINCIAS.ID_PROVINCIA = TBL_EMPRESA.ID_PROVINCIA
ORDER BY TBL_EMPRESA.ID_CIA;

CREATE OR REPLACE FORCE VIEW "FERREDB"."LISTAR_EMPREDETALLAD" ("CÓDIGO", "TIPO EMPRESA" ,"PERSONERIA", "Nº IDENTIFICACION", "RAZÓN SOCIAL","NOMBRE","PROVINCIA","DIRECCION","TELÉFONO 1","TELÉFONO 2","FAX","CP","WEB","EMAIL" , "ESTADO") AS 
SELECT TBL_EMPRESA.ID_CIA,
(SELECT TIPO_EMPRESA FROM TBL_TIPO_CIA WHERE ID_TIPO_CIA = TBL_EMPRESA.ID_TIPO_CIA), TBL_TIPO_IDENTIFICACION.PERSONERIA, TBL_EMPRESA.NUM_ID, TBL_EMPRESA.RAZON_SOCIAL,TBL_EMPRESA.NOMBRE,
(SELECT PROVINCIA FROM TBL_PROVINCIAS WHERE ID_PROVINCIA = TBL_EMPRESA.ID_PROVINCIA),TBL_EMPRESA.DIRECCION, TBL_EMPRESA.TEL1, TBL_EMPRESA.TEL2, TBL_EMPRESA.FAX, TBL_EMPRESA.CP, TBL_EMPRESA.WEB, TBL_EMPRESA.E_MAIL, TBL_EMPRESA.ESTADO
FROM TBL_EMPRESA, TBL_TIPO_IDENTIFICACION,TBL_TIPO_CIA, TBL_PROVINCIAS
WHERE TBL_TIPO_IDENTIFICACION.ID_TIPO_IDENTIFICACION = TBL_EMPRESA.ID_TIPO_IDENTIFICACION AND  TBL_TIPO_CIA.ID_TIPO_CIA = TBL_EMPRESA.ID_TIPO_CIA AND TBL_PROVINCIAS.ID_PROVINCIA = TBL_EMPRESA.ID_PROVINCIA
ORDER BY TBL_EMPRESA.ID_CIA;


create or replace PROCEDURE "LISTAR_TBL_EMPREDETALLADO" (REGISTROS OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN REGISTROS FOR SELECT * FROM LISTAR_EMPREDETALLAD;
END LISTAR_TBL_EMPREDETALLADO;