INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('001','AED','Dirham de los Emiratos Árabes Unidos');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('002','AFN','Afgani afgano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('003','ALL','Lek albano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('004','AMD','Dram armenio');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('005','ANG','Florín de las Antillas Holandesas');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('006','AOA','Kwanza angoleño');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('007','ARS','Peso argentino');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('008','AUD','Dólar australiano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('009','AWG','Florín arubeño');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('010','AZM','Manat azerbaiyano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('011','BAM','marco convertible de Bosnia-Herzegovina');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('012','BBD','Dólar de Barbados');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('013','BDT','Taka de Bangladesh');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('014','BGN','Lev búlgaro');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('015','BHD','Dinar bahreiní');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('016','BIF','Franco burundés');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('017','BMD','Dólar de Bermuda');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('018','BND','Dólar de Brunei');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('019','BOB','Boliviano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('020','BOV','Mvdol boliviano (código de fondos)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('021','BRL','Real brasileño');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('022','BSD','Dólar bahameño');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('023','BTN','Ngultrum de Bután');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('024','BWP','Pula de Botswana');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('025','BYR','Rublo bielorruso');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('026','BZD','Dólar de Belice');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('027','CAD','Dólar canadiense');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('028','CDF','Franco congoleño');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('029','CHF','Franco suizo');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('030','CLF','Unidades de fomento chilenas (código de fondos)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('031','CLP','Peso chileno');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('032','CNY','Yuan Renminbi de China');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('033','COP','Peso colombiano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('034','COU','Unidad de valor real colombiana (añadida al COP)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('035','CRC','Colón costarricense');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('036','CSD','Dinar serbio (It was replaced by RSD on October 25, 2006)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('037','CUP','Peso cubano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('038','CVE','Escudo caboverdiano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('039','CYP','Libra chipriota');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('040','CZK','Koruna checo');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('041','DJF','Franco yibutiano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('042','DKK','Corona danesa');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('043','DOP','Peso dominicano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('044','DZD','Dinar algerino');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('045','EEK','Corona estonia');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('046','EGP','Libra egipcia');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('047','ERN','Nakfa eritreo');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('048','ETB','Birr etíope');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('049','EUR','Euro');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('050','FJD','Dólar fijiano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('051','FKP','Libra malvinense');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('052','GBP','Libra esterlina (libra de Gran Bretaña)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('053','GEL','Lari georgiano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('054','GHC','Cedi ghanés');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('055','GIP','Libra de Gibraltar');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('056','GMD','Dalasi gambiano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('057','GNF','Franco guineano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('058','GTQ','Quetzal guatemalteco');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('059','GYD','Dólar guyanés');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('060','HKD','Dólar de Hong Kong');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('061','HNL','Lempira hondureño');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('062','HRK','Kuna croata');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('063','HTG','Gourde haitiano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('064','HUF','Forint húngaro');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('065','IDR','Rupiah indonesia');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('066','ILS','Nuevo shequel israelí');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('067','INR','Rupia india');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('068','IQD','Dinar iraqí');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('069','IRR','Rial iraní');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('070','ISK','Króna islandesa');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('071','JMD','Dólar jamaicano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('072','JOD','Dinar jordano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('073','JPY','Yen japonés');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('074','KES','Chelín keniata');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('075','KGS','Som kirguís (de Kirguistán)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('076','KHR','Riel camboyano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('077','KMF','Franco comoriano (de Comoras)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('078','KPW','Won norcoreano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('079','KRW','Won surcoreano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('080','KWD','Dinar kuwaití');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('081','KYD','Dólar caimano (de Islas Caimán)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('082','KZT','Tenge kazajo (de Kazajstán)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('083','LAK','Kip lao');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('084','LBP','Libra libanesa');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('085','LKR','Rupia de Sri Lanka');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('086','LRD','Dólar liberiano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('087','LSL','Loti lesothense (de Lesotho)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('088','LTL','Litas lituano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('089','LVL','Lat letón');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('090','LYD','Dinar libio');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('091','MAD','Dirham marroquí');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('092','MDL','Leu moldavo');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('093','MGA','Ariary malgache (de Madagascar)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('094','MKD','Denar macedonio');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('095','MMK','Kyat myanmaro');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('096','MNT','Tughrik mongol');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('097','MOP','Pataca de Macao');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('098','MRO','Ouguiya mauritana');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('099','MTL','Lira maltesa');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('100','MUR','Rupia mauricia');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('101','MVR','Rufiyaa maldiva');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('102','MWK','Kwacha malawiano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('103','MXN','Peso mexicano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('104','MXV','Unidad de Inversión (UDI) mexicana (código de fondos)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('105','MYR','Ringgit malayo');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('106','MZM','Metical mozambiqueño');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('107','NAD','Dólar namibio');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('108','NGN','Naira nigeriana');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('109','NIO','Córdoba nicaragüense');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('110','NOK','Corona noruega');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('111','NPR','Rupia nepalesa');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('112','NZD','Dólar neozelandés');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('113','OMR','Rial omaní (de Omán)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('114','PAB','Balboa panameña');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('115','PEN','Nuevo sol peruano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('116','PGK','Kina de Papúa Nueva Guinea');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('117','PHP','Peso filipino');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('118','PKR','Rupia pakistaní');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('119','PLN','zloty polaco');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('120','PYG','Guaraní paraguayo');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('121','QAR','Rial qatarí');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('122','RON','Leu rumano (desde el 1 de julio de 2005)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('123','RUB','Rublo ruso');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('124','RWF','Franco ruandés');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('125','SAR','Riyal saudí');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('126','SBD','Dólar de las Islas Salomón');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('127','SCR','Rupia de Seychelles');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('128','SDD','Dinar sudanés');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('129','SEK','Corona sueca');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('130','SGD','Dólar de Singapur');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('131','SHP','Libra de Santa Helena');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('132','SKK','Corona eslovaca');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('133','SLL','Leone de Sierra Leona');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('134','SOS','Chelín somalí');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('135','SRD','Dólar surinamés (desde el 1 de enero de 2004)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('136','STD','Dobra de Santo Tomé y Príncipe');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('137','SYP','Libra siria');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('138','SZL','Lilangeni suazi (de Suazilandia)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('139','THB','Baht tailandés');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('140','TJS','Somoni tayik (de Tayikistán)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('141','TMM','Manat turcomano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('142','TND','Dinar tunecino');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('143','TOP','Pa’anga tongano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('144','TRY','Nueva lira turca');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('145','TTD','Dólar de Trinidad y Tobago');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('146','TWD','Dólar taiwanés');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('147','TZS','Chelín tanzano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('148','UAH','Hryvnia ucraniana');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('149','UGX','Chelín ugandés');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('150','USD','Dólar estadounidense');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('151','USN','Dólar estadounidense (Siguiente día) (código de fondos)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('152','USS','United States dollar (Mismo día) (código de fondos)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('153','UYU','Peso uruguayo');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('154','UZS','Som uzbeco');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('155','VEB','Bolívar venezolano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('156','VEF','Bolívar fuerte venezolano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('157','VND','Dong vietnamita');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('158','VUV','Vatu vanuatense');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('159','WST','Tala samoana');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('160','XAF','Franco CFA');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('161','XAG','Onza de plata');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('162','XAU','Onza de oro');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('163','XBA','European Composite Unit (EURCO) (Bonds market unit)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('164','XBB','European Monetary Unit (E.M.U.-6) (Bonds market unit)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('165','XBC','European Unit of Account 9 (E.U.A.-9) (Bonds market unit)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('166','XBD','European Unit of Account 17 (E.U.A.-17) (Bonds market unit)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('167','XCD','Dólar del Caribe Oriental');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('168','XDR','Special Drawing Rights (FMI)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('169','XFO','Franco de oro (Special settlement currency)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('170','XFU','Franco UIC (Special settlement currency)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('171','XOF','Franco CFA');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('172','XPD','Onza de paladio');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('173','XPF','Franco CFP');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('174','XPT','Onza de platino');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('175','XTS','Reservado para pruebas');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('176','XXX','Sin divisa');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('177','YER','Rial yemení (de Yemen)');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('178','ZAR','Rand sudafricano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('179','ZMK','Kwacha zambiano');
INSERT INTO TBL_MONEDAS(ID_Moneda,Cod_Moneda,Descripcion) VALUES ('180','ZWD','Dólar zimbabuense');
commit;